  AccountServiceV1_0_0Lib|RedfishPocPkg/Library/RfishCS/edk2/AccountService/v1_0_0/Lib.inf
  AccountServiceV1_0_2Lib|RedfishPocPkg/Library/RfishCS/edk2/AccountService/v1_0_2/Lib.inf
  AccountServiceV1_0_3Lib|RedfishPocPkg/Library/RfishCS/edk2/AccountService/v1_0_3/Lib.inf
  AccountServiceV1_0_4Lib|RedfishPocPkg/Library/RfishCS/edk2/AccountService/v1_0_4/Lib.inf
  AccountServiceV1_0_5Lib|RedfishPocPkg/Library/RfishCS/edk2/AccountService/v1_0_5/Lib.inf
  AccountServiceV1_0_6Lib|RedfishPocPkg/Library/RfishCS/edk2/AccountService/v1_0_6/Lib.inf
  AccountServiceV1_1_0Lib|RedfishPocPkg/Library/RfishCS/edk2/AccountService/v1_1_0/Lib.inf
  AccountServiceV1_1_1Lib|RedfishPocPkg/Library/RfishCS/edk2/AccountService/v1_1_1/Lib.inf
  AccountServiceV1_1_2Lib|RedfishPocPkg/Library/RfishCS/edk2/AccountService/v1_1_2/Lib.inf
  AccountServiceV1_1_3Lib|RedfishPocPkg/Library/RfishCS/edk2/AccountService/v1_1_3/Lib.inf
  AccountServiceV1_2_0Lib|RedfishPocPkg/Library/RfishCS/edk2/AccountService/v1_2_0/Lib.inf
  AccountServiceV1_2_1Lib|RedfishPocPkg/Library/RfishCS/edk2/AccountService/v1_2_1/Lib.inf
  AccountServiceV1_2_2Lib|RedfishPocPkg/Library/RfishCS/edk2/AccountService/v1_2_2/Lib.inf
  AccountServiceV1_2_3Lib|RedfishPocPkg/Library/RfishCS/edk2/AccountService/v1_2_3/Lib.inf
  AccountServiceV1_3_0Lib|RedfishPocPkg/Library/RfishCS/edk2/AccountService/v1_3_0/Lib.inf
  AccountServiceV1_3_1Lib|RedfishPocPkg/Library/RfishCS/edk2/AccountService/v1_3_1/Lib.inf
  ActionInfoV1_0_0Lib|RedfishPocPkg/Library/RfishCS/edk2/ActionInfo/v1_0_0/Lib.inf
  ActionInfoV1_0_1Lib|RedfishPocPkg/Library/RfishCS/edk2/ActionInfo/v1_0_1/Lib.inf
  ActionInfoV1_0_2Lib|RedfishPocPkg/Library/RfishCS/edk2/ActionInfo/v1_0_2/Lib.inf
  ActionInfoV1_0_3Lib|RedfishPocPkg/Library/RfishCS/edk2/ActionInfo/v1_0_3/Lib.inf
  ActionInfoV1_0_4Lib|RedfishPocPkg/Library/RfishCS/edk2/ActionInfo/v1_0_4/Lib.inf
  ActionInfoV1_1_0Lib|RedfishPocPkg/Library/RfishCS/edk2/ActionInfo/v1_1_0/Lib.inf
  AssemblyV1_0_0Lib|RedfishPocPkg/Library/RfishCS/edk2/Assembly/v1_0_0/Lib.inf
  AssemblyV1_0_1Lib|RedfishPocPkg/Library/RfishCS/edk2/Assembly/v1_0_1/Lib.inf
  AssemblyV1_1_0Lib|RedfishPocPkg/Library/RfishCS/edk2/Assembly/v1_1_0/Lib.inf
  AssemblyV1_1_1Lib|RedfishPocPkg/Library/RfishCS/edk2/Assembly/v1_1_1/Lib.inf
  AssemblyV1_2_0Lib|RedfishPocPkg/Library/RfishCS/edk2/Assembly/v1_2_0/Lib.inf
  AttributeRegistryV1_0_0Lib|RedfishPocPkg/Library/RfishCS/edk2/AttributeRegistry/v1_0_0/Lib.inf
  AttributeRegistryV1_0_1Lib|RedfishPocPkg/Library/RfishCS/edk2/AttributeRegistry/v1_0_1/Lib.inf
  AttributeRegistryV1_0_2Lib|RedfishPocPkg/Library/RfishCS/edk2/AttributeRegistry/v1_0_2/Lib.inf
  AttributeRegistryV1_0_3Lib|RedfishPocPkg/Library/RfishCS/edk2/AttributeRegistry/v1_0_3/Lib.inf
  AttributeRegistryV1_0_4Lib|RedfishPocPkg/Library/RfishCS/edk2/AttributeRegistry/v1_0_4/Lib.inf
  AttributeRegistryV1_0_5Lib|RedfishPocPkg/Library/RfishCS/edk2/AttributeRegistry/v1_0_5/Lib.inf
  AttributeRegistryV1_1_0Lib|RedfishPocPkg/Library/RfishCS/edk2/AttributeRegistry/v1_1_0/Lib.inf
  AttributeRegistryV1_1_1Lib|RedfishPocPkg/Library/RfishCS/edk2/AttributeRegistry/v1_1_1/Lib.inf
  AttributeRegistryV1_1_2Lib|RedfishPocPkg/Library/RfishCS/edk2/AttributeRegistry/v1_1_2/Lib.inf
  AttributeRegistryV1_1_3Lib|RedfishPocPkg/Library/RfishCS/edk2/AttributeRegistry/v1_1_3/Lib.inf
  AttributeRegistryV1_1_4Lib|RedfishPocPkg/Library/RfishCS/edk2/AttributeRegistry/v1_1_4/Lib.inf
  AttributeRegistryV1_2_0Lib|RedfishPocPkg/Library/RfishCS/edk2/AttributeRegistry/v1_2_0/Lib.inf
  AttributeRegistryV1_2_1Lib|RedfishPocPkg/Library/RfishCS/edk2/AttributeRegistry/v1_2_1/Lib.inf
  AttributeRegistryV1_2_2Lib|RedfishPocPkg/Library/RfishCS/edk2/AttributeRegistry/v1_2_2/Lib.inf
  AttributeRegistryV1_3_0Lib|RedfishPocPkg/Library/RfishCS/edk2/AttributeRegistry/v1_3_0/Lib.inf
  BiosV1_0_0Lib|RedfishPocPkg/Library/RfishCS/edk2/Bios/v1_0_0/Lib.inf
  BiosV1_0_1Lib|RedfishPocPkg/Library/RfishCS/edk2/Bios/v1_0_1/Lib.inf
  BiosV1_0_2Lib|RedfishPocPkg/Library/RfishCS/edk2/Bios/v1_0_2/Lib.inf
  BiosV1_0_3Lib|RedfishPocPkg/Library/RfishCS/edk2/Bios/v1_0_3/Lib.inf
  BiosV1_0_4Lib|RedfishPocPkg/Library/RfishCS/edk2/Bios/v1_0_4/Lib.inf
  BiosV1_0_5Lib|RedfishPocPkg/Library/RfishCS/edk2/Bios/v1_0_5/Lib.inf
  BootOptionV1_0_0Lib|RedfishPocPkg/Library/RfishCS/edk2/BootOption/v1_0_0/Lib.inf
  BootOptionV1_0_1Lib|RedfishPocPkg/Library/RfishCS/edk2/BootOption/v1_0_1/Lib.inf
  BootOptionCollectionLib|RedfishPocPkg/Library/RfishCS/edk2/BootOptionCollection/Lib.inf
  ChassisV1_0_0Lib|RedfishPocPkg/Library/RfishCS/edk2/Chassis/v1_0_0/Lib.inf
  ChassisV1_0_1Lib|RedfishPocPkg/Library/RfishCS/edk2/Chassis/v1_0_1/Lib.inf
  ChassisV1_0_2Lib|RedfishPocPkg/Library/RfishCS/edk2/Chassis/v1_0_2/Lib.inf
  ChassisV1_0_3Lib|RedfishPocPkg/Library/RfishCS/edk2/Chassis/v1_0_3/Lib.inf
  ChassisV1_0_4Lib|RedfishPocPkg/Library/RfishCS/edk2/Chassis/v1_0_4/Lib.inf
  ChassisV1_0_5Lib|RedfishPocPkg/Library/RfishCS/edk2/Chassis/v1_0_5/Lib.inf
  ChassisV1_0_6Lib|RedfishPocPkg/Library/RfishCS/edk2/Chassis/v1_0_6/Lib.inf
  ChassisV1_0_7Lib|RedfishPocPkg/Library/RfishCS/edk2/Chassis/v1_0_7/Lib.inf
  ChassisV1_0_8Lib|RedfishPocPkg/Library/RfishCS/edk2/Chassis/v1_0_8/Lib.inf
  ChassisV1_1_0Lib|RedfishPocPkg/Library/RfishCS/edk2/Chassis/v1_1_0/Lib.inf
  ChassisV1_1_2Lib|RedfishPocPkg/Library/RfishCS/edk2/Chassis/v1_1_2/Lib.inf
  ChassisV1_1_3Lib|RedfishPocPkg/Library/RfishCS/edk2/Chassis/v1_1_3/Lib.inf
  ChassisV1_1_4Lib|RedfishPocPkg/Library/RfishCS/edk2/Chassis/v1_1_4/Lib.inf
  ChassisV1_1_5Lib|RedfishPocPkg/Library/RfishCS/edk2/Chassis/v1_1_5/Lib.inf
  ChassisV1_1_6Lib|RedfishPocPkg/Library/RfishCS/edk2/Chassis/v1_1_6/Lib.inf
  ChassisV1_1_7Lib|RedfishPocPkg/Library/RfishCS/edk2/Chassis/v1_1_7/Lib.inf
  ChassisV1_1_8Lib|RedfishPocPkg/Library/RfishCS/edk2/Chassis/v1_1_8/Lib.inf
  ChassisV1_2_0Lib|RedfishPocPkg/Library/RfishCS/edk2/Chassis/v1_2_0/Lib.inf
  ChassisV1_2_1Lib|RedfishPocPkg/Library/RfishCS/edk2/Chassis/v1_2_1/Lib.inf
  ChassisV1_2_2Lib|RedfishPocPkg/Library/RfishCS/edk2/Chassis/v1_2_2/Lib.inf
  ChassisV1_2_3Lib|RedfishPocPkg/Library/RfishCS/edk2/Chassis/v1_2_3/Lib.inf
  ChassisV1_2_4Lib|RedfishPocPkg/Library/RfishCS/edk2/Chassis/v1_2_4/Lib.inf
  ChassisV1_2_5Lib|RedfishPocPkg/Library/RfishCS/edk2/Chassis/v1_2_5/Lib.inf
  ChassisV1_2_6Lib|RedfishPocPkg/Library/RfishCS/edk2/Chassis/v1_2_6/Lib.inf
  ChassisV1_3_0Lib|RedfishPocPkg/Library/RfishCS/edk2/Chassis/v1_3_0/Lib.inf
  ChassisV1_3_1Lib|RedfishPocPkg/Library/RfishCS/edk2/Chassis/v1_3_1/Lib.inf
  ChassisV1_3_2Lib|RedfishPocPkg/Library/RfishCS/edk2/Chassis/v1_3_2/Lib.inf
  ChassisV1_3_3Lib|RedfishPocPkg/Library/RfishCS/edk2/Chassis/v1_3_3/Lib.inf
  ChassisV1_3_4Lib|RedfishPocPkg/Library/RfishCS/edk2/Chassis/v1_3_4/Lib.inf
  ChassisV1_3_5Lib|RedfishPocPkg/Library/RfishCS/edk2/Chassis/v1_3_5/Lib.inf
  ChassisV1_3_6Lib|RedfishPocPkg/Library/RfishCS/edk2/Chassis/v1_3_6/Lib.inf
  ChassisV1_4_0Lib|RedfishPocPkg/Library/RfishCS/edk2/Chassis/v1_4_0/Lib.inf
  ChassisV1_4_1Lib|RedfishPocPkg/Library/RfishCS/edk2/Chassis/v1_4_1/Lib.inf
  ChassisV1_4_2Lib|RedfishPocPkg/Library/RfishCS/edk2/Chassis/v1_4_2/Lib.inf
  ChassisV1_4_3Lib|RedfishPocPkg/Library/RfishCS/edk2/Chassis/v1_4_3/Lib.inf
  ChassisV1_4_4Lib|RedfishPocPkg/Library/RfishCS/edk2/Chassis/v1_4_4/Lib.inf
  ChassisV1_4_5Lib|RedfishPocPkg/Library/RfishCS/edk2/Chassis/v1_4_5/Lib.inf
  ChassisV1_5_0Lib|RedfishPocPkg/Library/RfishCS/edk2/Chassis/v1_5_0/Lib.inf
  ChassisV1_5_1Lib|RedfishPocPkg/Library/RfishCS/edk2/Chassis/v1_5_1/Lib.inf
  ChassisV1_5_2Lib|RedfishPocPkg/Library/RfishCS/edk2/Chassis/v1_5_2/Lib.inf
  ChassisV1_5_3Lib|RedfishPocPkg/Library/RfishCS/edk2/Chassis/v1_5_3/Lib.inf
  ChassisV1_5_4Lib|RedfishPocPkg/Library/RfishCS/edk2/Chassis/v1_5_4/Lib.inf
  ChassisV1_6_0Lib|RedfishPocPkg/Library/RfishCS/edk2/Chassis/v1_6_0/Lib.inf
  ChassisV1_6_1Lib|RedfishPocPkg/Library/RfishCS/edk2/Chassis/v1_6_1/Lib.inf
  ChassisV1_6_2Lib|RedfishPocPkg/Library/RfishCS/edk2/Chassis/v1_6_2/Lib.inf
  ChassisV1_7_0Lib|RedfishPocPkg/Library/RfishCS/edk2/Chassis/v1_7_0/Lib.inf
  ChassisV1_7_1Lib|RedfishPocPkg/Library/RfishCS/edk2/Chassis/v1_7_1/Lib.inf
  ChassisV1_7_2Lib|RedfishPocPkg/Library/RfishCS/edk2/Chassis/v1_7_2/Lib.inf
  ChassisV1_8_0Lib|RedfishPocPkg/Library/RfishCS/edk2/Chassis/v1_8_0/Lib.inf
  ChassisV1_8_1Lib|RedfishPocPkg/Library/RfishCS/edk2/Chassis/v1_8_1/Lib.inf
  ChassisCollectionLib|RedfishPocPkg/Library/RfishCS/edk2/ChassisCollection/Lib.inf
  CompositionServiceV1_0_0Lib|RedfishPocPkg/Library/RfishCS/edk2/CompositionService/v1_0_0/Lib.inf
  CompositionServiceV1_0_1Lib|RedfishPocPkg/Library/RfishCS/edk2/CompositionService/v1_0_1/Lib.inf
  CompositionServiceV1_0_2Lib|RedfishPocPkg/Library/RfishCS/edk2/CompositionService/v1_0_2/Lib.inf
  CompositionServiceV1_1_0Lib|RedfishPocPkg/Library/RfishCS/edk2/CompositionService/v1_1_0/Lib.inf
  ComputerSystemV1_0_0Lib|RedfishPocPkg/Library/RfishCS/edk2/ComputerSystem/v1_0_0/Lib.inf
  ComputerSystemV1_0_1Lib|RedfishPocPkg/Library/RfishCS/edk2/ComputerSystem/v1_0_1/Lib.inf
  ComputerSystemV1_0_2Lib|RedfishPocPkg/Library/RfishCS/edk2/ComputerSystem/v1_0_2/Lib.inf
  ComputerSystemV1_0_3Lib|RedfishPocPkg/Library/RfishCS/edk2/ComputerSystem/v1_0_3/Lib.inf
  ComputerSystemV1_0_4Lib|RedfishPocPkg/Library/RfishCS/edk2/ComputerSystem/v1_0_4/Lib.inf
  ComputerSystemV1_0_5Lib|RedfishPocPkg/Library/RfishCS/edk2/ComputerSystem/v1_0_5/Lib.inf
  ComputerSystemV1_0_6Lib|RedfishPocPkg/Library/RfishCS/edk2/ComputerSystem/v1_0_6/Lib.inf
  ComputerSystemV1_0_7Lib|RedfishPocPkg/Library/RfishCS/edk2/ComputerSystem/v1_0_7/Lib.inf
  ComputerSystemV1_0_8Lib|RedfishPocPkg/Library/RfishCS/edk2/ComputerSystem/v1_0_8/Lib.inf
  ComputerSystemV1_0_9Lib|RedfishPocPkg/Library/RfishCS/edk2/ComputerSystem/v1_0_9/Lib.inf
  ComputerSystemV1_1_0Lib|RedfishPocPkg/Library/RfishCS/edk2/ComputerSystem/v1_1_0/Lib.inf
  ComputerSystemV1_1_1Lib|RedfishPocPkg/Library/RfishCS/edk2/ComputerSystem/v1_1_1/Lib.inf
  ComputerSystemV1_1_2Lib|RedfishPocPkg/Library/RfishCS/edk2/ComputerSystem/v1_1_2/Lib.inf
  ComputerSystemV1_1_3Lib|RedfishPocPkg/Library/RfishCS/edk2/ComputerSystem/v1_1_3/Lib.inf
  ComputerSystemV1_1_4Lib|RedfishPocPkg/Library/RfishCS/edk2/ComputerSystem/v1_1_4/Lib.inf
  ComputerSystemV1_1_5Lib|RedfishPocPkg/Library/RfishCS/edk2/ComputerSystem/v1_1_5/Lib.inf
  ComputerSystemV1_1_6Lib|RedfishPocPkg/Library/RfishCS/edk2/ComputerSystem/v1_1_6/Lib.inf
  ComputerSystemV1_1_7Lib|RedfishPocPkg/Library/RfishCS/edk2/ComputerSystem/v1_1_7/Lib.inf
  ComputerSystemV1_2_0Lib|RedfishPocPkg/Library/RfishCS/edk2/ComputerSystem/v1_2_0/Lib.inf
  ComputerSystemV1_2_1Lib|RedfishPocPkg/Library/RfishCS/edk2/ComputerSystem/v1_2_1/Lib.inf
  ComputerSystemV1_2_2Lib|RedfishPocPkg/Library/RfishCS/edk2/ComputerSystem/v1_2_2/Lib.inf
  ComputerSystemV1_2_3Lib|RedfishPocPkg/Library/RfishCS/edk2/ComputerSystem/v1_2_3/Lib.inf
  ComputerSystemV1_2_4Lib|RedfishPocPkg/Library/RfishCS/edk2/ComputerSystem/v1_2_4/Lib.inf
  ComputerSystemV1_2_5Lib|RedfishPocPkg/Library/RfishCS/edk2/ComputerSystem/v1_2_5/Lib.inf
  ComputerSystemV1_2_6Lib|RedfishPocPkg/Library/RfishCS/edk2/ComputerSystem/v1_2_6/Lib.inf
  ComputerSystemV1_3_0Lib|RedfishPocPkg/Library/RfishCS/edk2/ComputerSystem/v1_3_0/Lib.inf
  ComputerSystemV1_3_1Lib|RedfishPocPkg/Library/RfishCS/edk2/ComputerSystem/v1_3_1/Lib.inf
  ComputerSystemV1_3_2Lib|RedfishPocPkg/Library/RfishCS/edk2/ComputerSystem/v1_3_2/Lib.inf
  ComputerSystemV1_3_3Lib|RedfishPocPkg/Library/RfishCS/edk2/ComputerSystem/v1_3_3/Lib.inf
  ComputerSystemV1_3_4Lib|RedfishPocPkg/Library/RfishCS/edk2/ComputerSystem/v1_3_4/Lib.inf
  ComputerSystemV1_3_5Lib|RedfishPocPkg/Library/RfishCS/edk2/ComputerSystem/v1_3_5/Lib.inf
  ComputerSystemV1_4_0Lib|RedfishPocPkg/Library/RfishCS/edk2/ComputerSystem/v1_4_0/Lib.inf
  ComputerSystemV1_4_1Lib|RedfishPocPkg/Library/RfishCS/edk2/ComputerSystem/v1_4_1/Lib.inf
  ComputerSystemV1_4_2Lib|RedfishPocPkg/Library/RfishCS/edk2/ComputerSystem/v1_4_2/Lib.inf
  ComputerSystemV1_4_3Lib|RedfishPocPkg/Library/RfishCS/edk2/ComputerSystem/v1_4_3/Lib.inf
  ComputerSystemV1_4_4Lib|RedfishPocPkg/Library/RfishCS/edk2/ComputerSystem/v1_4_4/Lib.inf
  ComputerSystemV1_5_0Lib|RedfishPocPkg/Library/RfishCS/edk2/ComputerSystem/v1_5_0/Lib.inf
  ComputerSystemV1_5_1Lib|RedfishPocPkg/Library/RfishCS/edk2/ComputerSystem/v1_5_1/Lib.inf
  ComputerSystemV1_5_2Lib|RedfishPocPkg/Library/RfishCS/edk2/ComputerSystem/v1_5_2/Lib.inf
  ComputerSystemCollectionLib|RedfishPocPkg/Library/RfishCS/edk2/ComputerSystemCollection/Lib.inf
  DriveV1_0_0Lib|RedfishPocPkg/Library/RfishCS/edk2/Drive/v1_0_0/Lib.inf
  DriveV1_0_1Lib|RedfishPocPkg/Library/RfishCS/edk2/Drive/v1_0_1/Lib.inf
  DriveV1_0_2Lib|RedfishPocPkg/Library/RfishCS/edk2/Drive/v1_0_2/Lib.inf
  DriveV1_0_3Lib|RedfishPocPkg/Library/RfishCS/edk2/Drive/v1_0_3/Lib.inf
  DriveV1_0_4Lib|RedfishPocPkg/Library/RfishCS/edk2/Drive/v1_0_4/Lib.inf
  DriveV1_0_5Lib|RedfishPocPkg/Library/RfishCS/edk2/Drive/v1_0_5/Lib.inf
  DriveV1_0_6Lib|RedfishPocPkg/Library/RfishCS/edk2/Drive/v1_0_6/Lib.inf
  DriveV1_1_0Lib|RedfishPocPkg/Library/RfishCS/edk2/Drive/v1_1_0/Lib.inf
  DriveV1_1_1Lib|RedfishPocPkg/Library/RfishCS/edk2/Drive/v1_1_1/Lib.inf
  DriveV1_1_2Lib|RedfishPocPkg/Library/RfishCS/edk2/Drive/v1_1_2/Lib.inf
  DriveV1_1_3Lib|RedfishPocPkg/Library/RfishCS/edk2/Drive/v1_1_3/Lib.inf
  DriveV1_1_4Lib|RedfishPocPkg/Library/RfishCS/edk2/Drive/v1_1_4/Lib.inf
  DriveV1_1_5Lib|RedfishPocPkg/Library/RfishCS/edk2/Drive/v1_1_5/Lib.inf
  DriveV1_2_0Lib|RedfishPocPkg/Library/RfishCS/edk2/Drive/v1_2_0/Lib.inf
  DriveV1_2_1Lib|RedfishPocPkg/Library/RfishCS/edk2/Drive/v1_2_1/Lib.inf
  DriveV1_2_2Lib|RedfishPocPkg/Library/RfishCS/edk2/Drive/v1_2_2/Lib.inf
  DriveV1_2_3Lib|RedfishPocPkg/Library/RfishCS/edk2/Drive/v1_2_3/Lib.inf
  DriveV1_3_0Lib|RedfishPocPkg/Library/RfishCS/edk2/Drive/v1_3_0/Lib.inf
  DriveV1_3_1Lib|RedfishPocPkg/Library/RfishCS/edk2/Drive/v1_3_1/Lib.inf
  DriveV1_3_2Lib|RedfishPocPkg/Library/RfishCS/edk2/Drive/v1_3_2/Lib.inf
  DriveV1_4_0Lib|RedfishPocPkg/Library/RfishCS/edk2/Drive/v1_4_0/Lib.inf
  DriveV1_4_1Lib|RedfishPocPkg/Library/RfishCS/edk2/Drive/v1_4_1/Lib.inf
  DriveV1_4_2Lib|RedfishPocPkg/Library/RfishCS/edk2/Drive/v1_4_2/Lib.inf
  DriveV1_5_0Lib|RedfishPocPkg/Library/RfishCS/edk2/Drive/v1_5_0/Lib.inf
  DriveV1_5_1Lib|RedfishPocPkg/Library/RfishCS/edk2/Drive/v1_5_1/Lib.inf
  EndpointV1_0_0Lib|RedfishPocPkg/Library/RfishCS/edk2/Endpoint/v1_0_0/Lib.inf
  EndpointV1_0_1Lib|RedfishPocPkg/Library/RfishCS/edk2/Endpoint/v1_0_1/Lib.inf
  EndpointV1_0_2Lib|RedfishPocPkg/Library/RfishCS/edk2/Endpoint/v1_0_2/Lib.inf
  EndpointV1_0_3Lib|RedfishPocPkg/Library/RfishCS/edk2/Endpoint/v1_0_3/Lib.inf
  EndpointV1_0_4Lib|RedfishPocPkg/Library/RfishCS/edk2/Endpoint/v1_0_4/Lib.inf
  EndpointV1_0_5Lib|RedfishPocPkg/Library/RfishCS/edk2/Endpoint/v1_0_5/Lib.inf
  EndpointV1_1_0Lib|RedfishPocPkg/Library/RfishCS/edk2/Endpoint/v1_1_0/Lib.inf
  EndpointV1_1_1Lib|RedfishPocPkg/Library/RfishCS/edk2/Endpoint/v1_1_1/Lib.inf
  EndpointV1_1_2Lib|RedfishPocPkg/Library/RfishCS/edk2/Endpoint/v1_1_2/Lib.inf
  EndpointV1_2_0Lib|RedfishPocPkg/Library/RfishCS/edk2/Endpoint/v1_2_0/Lib.inf
  EndpointV1_2_1Lib|RedfishPocPkg/Library/RfishCS/edk2/Endpoint/v1_2_1/Lib.inf
  EndpointCollectionLib|RedfishPocPkg/Library/RfishCS/edk2/EndpointCollection/Lib.inf
  EthernetInterfaceV1_0_0Lib|RedfishPocPkg/Library/RfishCS/edk2/EthernetInterface/v1_0_0/Lib.inf
  EthernetInterfaceV1_0_2Lib|RedfishPocPkg/Library/RfishCS/edk2/EthernetInterface/v1_0_2/Lib.inf
  EthernetInterfaceV1_0_3Lib|RedfishPocPkg/Library/RfishCS/edk2/EthernetInterface/v1_0_3/Lib.inf
  EthernetInterfaceV1_0_4Lib|RedfishPocPkg/Library/RfishCS/edk2/EthernetInterface/v1_0_4/Lib.inf
  EthernetInterfaceV1_0_5Lib|RedfishPocPkg/Library/RfishCS/edk2/EthernetInterface/v1_0_5/Lib.inf
  EthernetInterfaceV1_0_6Lib|RedfishPocPkg/Library/RfishCS/edk2/EthernetInterface/v1_0_6/Lib.inf
  EthernetInterfaceV1_1_0Lib|RedfishPocPkg/Library/RfishCS/edk2/EthernetInterface/v1_1_0/Lib.inf
  EthernetInterfaceV1_1_1Lib|RedfishPocPkg/Library/RfishCS/edk2/EthernetInterface/v1_1_1/Lib.inf
  EthernetInterfaceV1_1_2Lib|RedfishPocPkg/Library/RfishCS/edk2/EthernetInterface/v1_1_2/Lib.inf
  EthernetInterfaceV1_1_3Lib|RedfishPocPkg/Library/RfishCS/edk2/EthernetInterface/v1_1_3/Lib.inf
  EthernetInterfaceV1_1_4Lib|RedfishPocPkg/Library/RfishCS/edk2/EthernetInterface/v1_1_4/Lib.inf
  EthernetInterfaceV1_2_0Lib|RedfishPocPkg/Library/RfishCS/edk2/EthernetInterface/v1_2_0/Lib.inf
  EthernetInterfaceV1_2_1Lib|RedfishPocPkg/Library/RfishCS/edk2/EthernetInterface/v1_2_1/Lib.inf
  EthernetInterfaceV1_2_2Lib|RedfishPocPkg/Library/RfishCS/edk2/EthernetInterface/v1_2_2/Lib.inf
  EthernetInterfaceV1_2_3Lib|RedfishPocPkg/Library/RfishCS/edk2/EthernetInterface/v1_2_3/Lib.inf
  EthernetInterfaceV1_3_0Lib|RedfishPocPkg/Library/RfishCS/edk2/EthernetInterface/v1_3_0/Lib.inf
  EthernetInterfaceV1_3_1Lib|RedfishPocPkg/Library/RfishCS/edk2/EthernetInterface/v1_3_1/Lib.inf
  EthernetInterfaceV1_3_2Lib|RedfishPocPkg/Library/RfishCS/edk2/EthernetInterface/v1_3_2/Lib.inf
  EthernetInterfaceV1_4_0Lib|RedfishPocPkg/Library/RfishCS/edk2/EthernetInterface/v1_4_0/Lib.inf
  EthernetInterfaceV1_4_1Lib|RedfishPocPkg/Library/RfishCS/edk2/EthernetInterface/v1_4_1/Lib.inf
  EthernetInterfaceCollectionLib|RedfishPocPkg/Library/RfishCS/edk2/EthernetInterfaceCollection/Lib.inf
  EventV1_0_0Lib|RedfishPocPkg/Library/RfishCS/edk2/Event/v1_0_0/Lib.inf
  EventV1_0_2Lib|RedfishPocPkg/Library/RfishCS/edk2/Event/v1_0_2/Lib.inf
  EventV1_0_3Lib|RedfishPocPkg/Library/RfishCS/edk2/Event/v1_0_3/Lib.inf
  EventV1_0_4Lib|RedfishPocPkg/Library/RfishCS/edk2/Event/v1_0_4/Lib.inf
  EventV1_0_5Lib|RedfishPocPkg/Library/RfishCS/edk2/Event/v1_0_5/Lib.inf
  EventV1_0_6Lib|RedfishPocPkg/Library/RfishCS/edk2/Event/v1_0_6/Lib.inf
  EventV1_0_7Lib|RedfishPocPkg/Library/RfishCS/edk2/Event/v1_0_7/Lib.inf
  EventV1_0_8Lib|RedfishPocPkg/Library/RfishCS/edk2/Event/v1_0_8/Lib.inf
  EventV1_1_0Lib|RedfishPocPkg/Library/RfishCS/edk2/Event/v1_1_0/Lib.inf
  EventV1_1_1Lib|RedfishPocPkg/Library/RfishCS/edk2/Event/v1_1_1/Lib.inf
  EventV1_1_2Lib|RedfishPocPkg/Library/RfishCS/edk2/Event/v1_1_2/Lib.inf
  EventV1_1_3Lib|RedfishPocPkg/Library/RfishCS/edk2/Event/v1_1_3/Lib.inf
  EventV1_1_4Lib|RedfishPocPkg/Library/RfishCS/edk2/Event/v1_1_4/Lib.inf
  EventV1_1_5Lib|RedfishPocPkg/Library/RfishCS/edk2/Event/v1_1_5/Lib.inf
  EventV1_1_6Lib|RedfishPocPkg/Library/RfishCS/edk2/Event/v1_1_6/Lib.inf
  EventV1_2_0Lib|RedfishPocPkg/Library/RfishCS/edk2/Event/v1_2_0/Lib.inf
  EventV1_2_1Lib|RedfishPocPkg/Library/RfishCS/edk2/Event/v1_2_1/Lib.inf
  EventV1_2_2Lib|RedfishPocPkg/Library/RfishCS/edk2/Event/v1_2_2/Lib.inf
  EventV1_2_3Lib|RedfishPocPkg/Library/RfishCS/edk2/Event/v1_2_3/Lib.inf
  EventV1_3_0Lib|RedfishPocPkg/Library/RfishCS/edk2/Event/v1_3_0/Lib.inf
  EventV1_3_1Lib|RedfishPocPkg/Library/RfishCS/edk2/Event/v1_3_1/Lib.inf
  EventDestinationV1_0_0Lib|RedfishPocPkg/Library/RfishCS/edk2/EventDestination/v1_0_0/Lib.inf
  EventDestinationV1_0_2Lib|RedfishPocPkg/Library/RfishCS/edk2/EventDestination/v1_0_2/Lib.inf
  EventDestinationV1_0_3Lib|RedfishPocPkg/Library/RfishCS/edk2/EventDestination/v1_0_3/Lib.inf
  EventDestinationV1_0_4Lib|RedfishPocPkg/Library/RfishCS/edk2/EventDestination/v1_0_4/Lib.inf
  EventDestinationV1_0_5Lib|RedfishPocPkg/Library/RfishCS/edk2/EventDestination/v1_0_5/Lib.inf
  EventDestinationV1_0_6Lib|RedfishPocPkg/Library/RfishCS/edk2/EventDestination/v1_0_6/Lib.inf
  EventDestinationV1_1_0Lib|RedfishPocPkg/Library/RfishCS/edk2/EventDestination/v1_1_0/Lib.inf
  EventDestinationV1_1_1Lib|RedfishPocPkg/Library/RfishCS/edk2/EventDestination/v1_1_1/Lib.inf
  EventDestinationV1_1_2Lib|RedfishPocPkg/Library/RfishCS/edk2/EventDestination/v1_1_2/Lib.inf
  EventDestinationV1_1_3Lib|RedfishPocPkg/Library/RfishCS/edk2/EventDestination/v1_1_3/Lib.inf
  EventDestinationV1_1_4Lib|RedfishPocPkg/Library/RfishCS/edk2/EventDestination/v1_1_4/Lib.inf
  EventDestinationV1_1_5Lib|RedfishPocPkg/Library/RfishCS/edk2/EventDestination/v1_1_5/Lib.inf
  EventDestinationV1_2_0Lib|RedfishPocPkg/Library/RfishCS/edk2/EventDestination/v1_2_0/Lib.inf
  EventDestinationV1_2_1Lib|RedfishPocPkg/Library/RfishCS/edk2/EventDestination/v1_2_1/Lib.inf
  EventDestinationV1_2_2Lib|RedfishPocPkg/Library/RfishCS/edk2/EventDestination/v1_2_2/Lib.inf
  EventDestinationV1_2_3Lib|RedfishPocPkg/Library/RfishCS/edk2/EventDestination/v1_2_3/Lib.inf
  EventDestinationV1_3_0Lib|RedfishPocPkg/Library/RfishCS/edk2/EventDestination/v1_3_0/Lib.inf
  EventDestinationV1_3_1Lib|RedfishPocPkg/Library/RfishCS/edk2/EventDestination/v1_3_1/Lib.inf
  EventDestinationV1_4_0Lib|RedfishPocPkg/Library/RfishCS/edk2/EventDestination/v1_4_0/Lib.inf
  EventDestinationCollectionLib|RedfishPocPkg/Library/RfishCS/edk2/EventDestinationCollection/Lib.inf
  EventServiceV1_0_0Lib|RedfishPocPkg/Library/RfishCS/edk2/EventService/v1_0_0/Lib.inf
  EventServiceV1_0_2Lib|RedfishPocPkg/Library/RfishCS/edk2/EventService/v1_0_2/Lib.inf
  EventServiceV1_0_3Lib|RedfishPocPkg/Library/RfishCS/edk2/EventService/v1_0_3/Lib.inf
  EventServiceV1_0_4Lib|RedfishPocPkg/Library/RfishCS/edk2/EventService/v1_0_4/Lib.inf
  EventServiceV1_0_5Lib|RedfishPocPkg/Library/RfishCS/edk2/EventService/v1_0_5/Lib.inf
  EventServiceV1_0_6Lib|RedfishPocPkg/Library/RfishCS/edk2/EventService/v1_0_6/Lib.inf
  EventServiceV1_0_7Lib|RedfishPocPkg/Library/RfishCS/edk2/EventService/v1_0_7/Lib.inf
  EventServiceV1_0_8Lib|RedfishPocPkg/Library/RfishCS/edk2/EventService/v1_0_8/Lib.inf
  EventServiceV1_1_0Lib|RedfishPocPkg/Library/RfishCS/edk2/EventService/v1_1_0/Lib.inf
  EventServiceV1_1_1Lib|RedfishPocPkg/Library/RfishCS/edk2/EventService/v1_1_1/Lib.inf
  EventServiceV1_2_0Lib|RedfishPocPkg/Library/RfishCS/edk2/EventService/v1_2_0/Lib.inf
  ExternalAccountProviderV1_0_0Lib|RedfishPocPkg/Library/RfishCS/edk2/ExternalAccountProvider/v1_0_0/Lib.inf
  ExternalAccountProviderV1_0_1Lib|RedfishPocPkg/Library/RfishCS/edk2/ExternalAccountProvider/v1_0_1/Lib.inf
  ExternalAccountProviderCollectionLib|RedfishPocPkg/Library/RfishCS/edk2/ExternalAccountProviderCollection/Lib.inf
  FabricV1_0_0Lib|RedfishPocPkg/Library/RfishCS/edk2/Fabric/v1_0_0/Lib.inf
  FabricV1_0_1Lib|RedfishPocPkg/Library/RfishCS/edk2/Fabric/v1_0_1/Lib.inf
  FabricV1_0_2Lib|RedfishPocPkg/Library/RfishCS/edk2/Fabric/v1_0_2/Lib.inf
  FabricV1_0_3Lib|RedfishPocPkg/Library/RfishCS/edk2/Fabric/v1_0_3/Lib.inf
  FabricV1_0_4Lib|RedfishPocPkg/Library/RfishCS/edk2/Fabric/v1_0_4/Lib.inf
  FabricCollectionLib|RedfishPocPkg/Library/RfishCS/edk2/FabricCollection/Lib.inf
  HostInterfaceV1_0_0Lib|RedfishPocPkg/Library/RfishCS/edk2/HostInterface/v1_0_0/Lib.inf
  HostInterfaceV1_0_1Lib|RedfishPocPkg/Library/RfishCS/edk2/HostInterface/v1_0_1/Lib.inf
  HostInterfaceV1_0_2Lib|RedfishPocPkg/Library/RfishCS/edk2/HostInterface/v1_0_2/Lib.inf
  HostInterfaceV1_0_3Lib|RedfishPocPkg/Library/RfishCS/edk2/HostInterface/v1_0_3/Lib.inf
  HostInterfaceV1_1_0Lib|RedfishPocPkg/Library/RfishCS/edk2/HostInterface/v1_1_0/Lib.inf
  HostInterfaceV1_1_1Lib|RedfishPocPkg/Library/RfishCS/edk2/HostInterface/v1_1_1/Lib.inf
  HostInterfaceV1_1_2Lib|RedfishPocPkg/Library/RfishCS/edk2/HostInterface/v1_1_2/Lib.inf
  HostInterfaceV1_1_3Lib|RedfishPocPkg/Library/RfishCS/edk2/HostInterface/v1_1_3/Lib.inf
  HostInterfaceV1_2_0Lib|RedfishPocPkg/Library/RfishCS/edk2/HostInterface/v1_2_0/Lib.inf
  HostInterfaceCollectionLib|RedfishPocPkg/Library/RfishCS/edk2/HostInterfaceCollection/Lib.inf
  JobV1_0_0Lib|RedfishPocPkg/Library/RfishCS/edk2/Job/v1_0_0/Lib.inf
  JobCollectionLib|RedfishPocPkg/Library/RfishCS/edk2/JobCollection/Lib.inf
  JobServiceV1_0_0Lib|RedfishPocPkg/Library/RfishCS/edk2/JobService/v1_0_0/Lib.inf
  JsonSchemaFileV1_0_0Lib|RedfishPocPkg/Library/RfishCS/edk2/JsonSchemaFile/v1_0_0/Lib.inf
  JsonSchemaFileV1_0_2Lib|RedfishPocPkg/Library/RfishCS/edk2/JsonSchemaFile/v1_0_2/Lib.inf
  JsonSchemaFileV1_0_3Lib|RedfishPocPkg/Library/RfishCS/edk2/JsonSchemaFile/v1_0_3/Lib.inf
  JsonSchemaFileV1_0_4Lib|RedfishPocPkg/Library/RfishCS/edk2/JsonSchemaFile/v1_0_4/Lib.inf
  JsonSchemaFileV1_0_5Lib|RedfishPocPkg/Library/RfishCS/edk2/JsonSchemaFile/v1_0_5/Lib.inf
  JsonSchemaFileV1_1_0Lib|RedfishPocPkg/Library/RfishCS/edk2/JsonSchemaFile/v1_1_0/Lib.inf
  JsonSchemaFileV1_1_1Lib|RedfishPocPkg/Library/RfishCS/edk2/JsonSchemaFile/v1_1_1/Lib.inf
  JsonSchemaFileCollectionLib|RedfishPocPkg/Library/RfishCS/edk2/JsonSchemaFileCollection/Lib.inf
  LogEntryV1_0_0Lib|RedfishPocPkg/Library/RfishCS/edk2/LogEntry/v1_0_0/Lib.inf
  LogEntryV1_0_2Lib|RedfishPocPkg/Library/RfishCS/edk2/LogEntry/v1_0_2/Lib.inf
  LogEntryV1_0_3Lib|RedfishPocPkg/Library/RfishCS/edk2/LogEntry/v1_0_3/Lib.inf
  LogEntryV1_0_4Lib|RedfishPocPkg/Library/RfishCS/edk2/LogEntry/v1_0_4/Lib.inf
  LogEntryV1_0_5Lib|RedfishPocPkg/Library/RfishCS/edk2/LogEntry/v1_0_5/Lib.inf
  LogEntryV1_0_6Lib|RedfishPocPkg/Library/RfishCS/edk2/LogEntry/v1_0_6/Lib.inf
  LogEntryV1_0_7Lib|RedfishPocPkg/Library/RfishCS/edk2/LogEntry/v1_0_7/Lib.inf
  LogEntryV1_1_0Lib|RedfishPocPkg/Library/RfishCS/edk2/LogEntry/v1_1_0/Lib.inf
  LogEntryV1_1_1Lib|RedfishPocPkg/Library/RfishCS/edk2/LogEntry/v1_1_1/Lib.inf
  LogEntryV1_1_2Lib|RedfishPocPkg/Library/RfishCS/edk2/LogEntry/v1_1_2/Lib.inf
  LogEntryV1_1_3Lib|RedfishPocPkg/Library/RfishCS/edk2/LogEntry/v1_1_3/Lib.inf
  LogEntryV1_1_4Lib|RedfishPocPkg/Library/RfishCS/edk2/LogEntry/v1_1_4/Lib.inf
  LogEntryV1_1_5Lib|RedfishPocPkg/Library/RfishCS/edk2/LogEntry/v1_1_5/Lib.inf
  LogEntryV1_2_0Lib|RedfishPocPkg/Library/RfishCS/edk2/LogEntry/v1_2_0/Lib.inf
  LogEntryV1_2_1Lib|RedfishPocPkg/Library/RfishCS/edk2/LogEntry/v1_2_1/Lib.inf
  LogEntryV1_2_2Lib|RedfishPocPkg/Library/RfishCS/edk2/LogEntry/v1_2_2/Lib.inf
  LogEntryV1_2_3Lib|RedfishPocPkg/Library/RfishCS/edk2/LogEntry/v1_2_3/Lib.inf
  LogEntryV1_3_0Lib|RedfishPocPkg/Library/RfishCS/edk2/LogEntry/v1_3_0/Lib.inf
  LogEntryV1_3_1Lib|RedfishPocPkg/Library/RfishCS/edk2/LogEntry/v1_3_1/Lib.inf
  LogEntryV1_3_2Lib|RedfishPocPkg/Library/RfishCS/edk2/LogEntry/v1_3_2/Lib.inf
  LogEntryV1_4_0Lib|RedfishPocPkg/Library/RfishCS/edk2/LogEntry/v1_4_0/Lib.inf
  LogEntryV1_4_1Lib|RedfishPocPkg/Library/RfishCS/edk2/LogEntry/v1_4_1/Lib.inf
  LogEntryCollectionLib|RedfishPocPkg/Library/RfishCS/edk2/LogEntryCollection/Lib.inf
  LogServiceV1_0_0Lib|RedfishPocPkg/Library/RfishCS/edk2/LogService/v1_0_0/Lib.inf
  LogServiceV1_0_2Lib|RedfishPocPkg/Library/RfishCS/edk2/LogService/v1_0_2/Lib.inf
  LogServiceV1_0_3Lib|RedfishPocPkg/Library/RfishCS/edk2/LogService/v1_0_3/Lib.inf
  LogServiceV1_0_4Lib|RedfishPocPkg/Library/RfishCS/edk2/LogService/v1_0_4/Lib.inf
  LogServiceV1_0_5Lib|RedfishPocPkg/Library/RfishCS/edk2/LogService/v1_0_5/Lib.inf
  LogServiceV1_0_6Lib|RedfishPocPkg/Library/RfishCS/edk2/LogService/v1_0_6/Lib.inf
  LogServiceV1_1_0Lib|RedfishPocPkg/Library/RfishCS/edk2/LogService/v1_1_0/Lib.inf
  LogServiceV1_1_1Lib|RedfishPocPkg/Library/RfishCS/edk2/LogService/v1_1_1/Lib.inf
  LogServiceCollectionLib|RedfishPocPkg/Library/RfishCS/edk2/LogServiceCollection/Lib.inf
  ManagerV1_0_0Lib|RedfishPocPkg/Library/RfishCS/edk2/Manager/v1_0_0/Lib.inf
  ManagerV1_0_1Lib|RedfishPocPkg/Library/RfishCS/edk2/Manager/v1_0_1/Lib.inf
  ManagerV1_0_2Lib|RedfishPocPkg/Library/RfishCS/edk2/Manager/v1_0_2/Lib.inf
  ManagerV1_0_3Lib|RedfishPocPkg/Library/RfishCS/edk2/Manager/v1_0_3/Lib.inf
  ManagerV1_0_4Lib|RedfishPocPkg/Library/RfishCS/edk2/Manager/v1_0_4/Lib.inf
  ManagerV1_0_5Lib|RedfishPocPkg/Library/RfishCS/edk2/Manager/v1_0_5/Lib.inf
  ManagerV1_0_6Lib|RedfishPocPkg/Library/RfishCS/edk2/Manager/v1_0_6/Lib.inf
  ManagerV1_0_7Lib|RedfishPocPkg/Library/RfishCS/edk2/Manager/v1_0_7/Lib.inf
  ManagerV1_0_8Lib|RedfishPocPkg/Library/RfishCS/edk2/Manager/v1_0_8/Lib.inf
  ManagerV1_1_0Lib|RedfishPocPkg/Library/RfishCS/edk2/Manager/v1_1_0/Lib.inf
  ManagerV1_1_1Lib|RedfishPocPkg/Library/RfishCS/edk2/Manager/v1_1_1/Lib.inf
  ManagerV1_1_2Lib|RedfishPocPkg/Library/RfishCS/edk2/Manager/v1_1_2/Lib.inf
  ManagerV1_1_3Lib|RedfishPocPkg/Library/RfishCS/edk2/Manager/v1_1_3/Lib.inf
  ManagerV1_1_4Lib|RedfishPocPkg/Library/RfishCS/edk2/Manager/v1_1_4/Lib.inf
  ManagerV1_1_5Lib|RedfishPocPkg/Library/RfishCS/edk2/Manager/v1_1_5/Lib.inf
  ManagerV1_1_6Lib|RedfishPocPkg/Library/RfishCS/edk2/Manager/v1_1_6/Lib.inf
  ManagerV1_2_0Lib|RedfishPocPkg/Library/RfishCS/edk2/Manager/v1_2_0/Lib.inf
  ManagerV1_2_1Lib|RedfishPocPkg/Library/RfishCS/edk2/Manager/v1_2_1/Lib.inf
  ManagerV1_2_2Lib|RedfishPocPkg/Library/RfishCS/edk2/Manager/v1_2_2/Lib.inf
  ManagerV1_2_3Lib|RedfishPocPkg/Library/RfishCS/edk2/Manager/v1_2_3/Lib.inf
  ManagerV1_2_4Lib|RedfishPocPkg/Library/RfishCS/edk2/Manager/v1_2_4/Lib.inf
  ManagerV1_2_5Lib|RedfishPocPkg/Library/RfishCS/edk2/Manager/v1_2_5/Lib.inf
  ManagerV1_2_6Lib|RedfishPocPkg/Library/RfishCS/edk2/Manager/v1_2_6/Lib.inf
  ManagerV1_3_0Lib|RedfishPocPkg/Library/RfishCS/edk2/Manager/v1_3_0/Lib.inf
  ManagerV1_3_1Lib|RedfishPocPkg/Library/RfishCS/edk2/Manager/v1_3_1/Lib.inf
  ManagerV1_3_2Lib|RedfishPocPkg/Library/RfishCS/edk2/Manager/v1_3_2/Lib.inf
  ManagerV1_3_3Lib|RedfishPocPkg/Library/RfishCS/edk2/Manager/v1_3_3/Lib.inf
  ManagerV1_3_4Lib|RedfishPocPkg/Library/RfishCS/edk2/Manager/v1_3_4/Lib.inf
  ManagerV1_3_5Lib|RedfishPocPkg/Library/RfishCS/edk2/Manager/v1_3_5/Lib.inf
  ManagerV1_4_0Lib|RedfishPocPkg/Library/RfishCS/edk2/Manager/v1_4_0/Lib.inf
  ManagerV1_4_1Lib|RedfishPocPkg/Library/RfishCS/edk2/Manager/v1_4_1/Lib.inf
  ManagerV1_4_2Lib|RedfishPocPkg/Library/RfishCS/edk2/Manager/v1_4_2/Lib.inf
  ManagerV1_5_0Lib|RedfishPocPkg/Library/RfishCS/edk2/Manager/v1_5_0/Lib.inf
  ManagerV1_5_1Lib|RedfishPocPkg/Library/RfishCS/edk2/Manager/v1_5_1/Lib.inf
  ManagerAccountV1_0_0Lib|RedfishPocPkg/Library/RfishCS/edk2/ManagerAccount/v1_0_0/Lib.inf
  ManagerAccountV1_0_2Lib|RedfishPocPkg/Library/RfishCS/edk2/ManagerAccount/v1_0_2/Lib.inf
  ManagerAccountV1_0_3Lib|RedfishPocPkg/Library/RfishCS/edk2/ManagerAccount/v1_0_3/Lib.inf
  ManagerAccountV1_0_4Lib|RedfishPocPkg/Library/RfishCS/edk2/ManagerAccount/v1_0_4/Lib.inf
  ManagerAccountV1_0_5Lib|RedfishPocPkg/Library/RfishCS/edk2/ManagerAccount/v1_0_5/Lib.inf
  ManagerAccountV1_0_6Lib|RedfishPocPkg/Library/RfishCS/edk2/ManagerAccount/v1_0_6/Lib.inf
  ManagerAccountV1_0_7Lib|RedfishPocPkg/Library/RfishCS/edk2/ManagerAccount/v1_0_7/Lib.inf
  ManagerAccountV1_1_0Lib|RedfishPocPkg/Library/RfishCS/edk2/ManagerAccount/v1_1_0/Lib.inf
  ManagerAccountV1_1_1Lib|RedfishPocPkg/Library/RfishCS/edk2/ManagerAccount/v1_1_1/Lib.inf
  ManagerAccountV1_1_2Lib|RedfishPocPkg/Library/RfishCS/edk2/ManagerAccount/v1_1_2/Lib.inf
  ManagerAccountV1_1_3Lib|RedfishPocPkg/Library/RfishCS/edk2/ManagerAccount/v1_1_3/Lib.inf
  ManagerAccountCollectionLib|RedfishPocPkg/Library/RfishCS/edk2/ManagerAccountCollection/Lib.inf
  ManagerCollectionLib|RedfishPocPkg/Library/RfishCS/edk2/ManagerCollection/Lib.inf
  ManagerNetworkProtocolV1_0_0Lib|RedfishPocPkg/Library/RfishCS/edk2/ManagerNetworkProtocol/v1_0_0/Lib.inf
  ManagerNetworkProtocolV1_0_2Lib|RedfishPocPkg/Library/RfishCS/edk2/ManagerNetworkProtocol/v1_0_2/Lib.inf
  ManagerNetworkProtocolV1_0_3Lib|RedfishPocPkg/Library/RfishCS/edk2/ManagerNetworkProtocol/v1_0_3/Lib.inf
  ManagerNetworkProtocolV1_0_4Lib|RedfishPocPkg/Library/RfishCS/edk2/ManagerNetworkProtocol/v1_0_4/Lib.inf
  ManagerNetworkProtocolV1_0_5Lib|RedfishPocPkg/Library/RfishCS/edk2/ManagerNetworkProtocol/v1_0_5/Lib.inf
  ManagerNetworkProtocolV1_1_0Lib|RedfishPocPkg/Library/RfishCS/edk2/ManagerNetworkProtocol/v1_1_0/Lib.inf
  ManagerNetworkProtocolV1_1_1Lib|RedfishPocPkg/Library/RfishCS/edk2/ManagerNetworkProtocol/v1_1_1/Lib.inf
  ManagerNetworkProtocolV1_1_2Lib|RedfishPocPkg/Library/RfishCS/edk2/ManagerNetworkProtocol/v1_1_2/Lib.inf
  ManagerNetworkProtocolV1_2_0Lib|RedfishPocPkg/Library/RfishCS/edk2/ManagerNetworkProtocol/v1_2_0/Lib.inf
  ManagerNetworkProtocolV1_2_1Lib|RedfishPocPkg/Library/RfishCS/edk2/ManagerNetworkProtocol/v1_2_1/Lib.inf
  ManagerNetworkProtocolV1_3_0Lib|RedfishPocPkg/Library/RfishCS/edk2/ManagerNetworkProtocol/v1_3_0/Lib.inf
  MemoryV1_0_0Lib|RedfishPocPkg/Library/RfishCS/edk2/Memory/v1_0_0/Lib.inf
  MemoryV1_0_1Lib|RedfishPocPkg/Library/RfishCS/edk2/Memory/v1_0_1/Lib.inf
  MemoryV1_0_2Lib|RedfishPocPkg/Library/RfishCS/edk2/Memory/v1_0_2/Lib.inf
  MemoryV1_0_3Lib|RedfishPocPkg/Library/RfishCS/edk2/Memory/v1_0_3/Lib.inf
  MemoryV1_0_4Lib|RedfishPocPkg/Library/RfishCS/edk2/Memory/v1_0_4/Lib.inf
  MemoryV1_0_5Lib|RedfishPocPkg/Library/RfishCS/edk2/Memory/v1_0_5/Lib.inf
  MemoryV1_1_0Lib|RedfishPocPkg/Library/RfishCS/edk2/Memory/v1_1_0/Lib.inf
  MemoryV1_1_1Lib|RedfishPocPkg/Library/RfishCS/edk2/Memory/v1_1_1/Lib.inf
  MemoryV1_1_2Lib|RedfishPocPkg/Library/RfishCS/edk2/Memory/v1_1_2/Lib.inf
  MemoryV1_1_3Lib|RedfishPocPkg/Library/RfishCS/edk2/Memory/v1_1_3/Lib.inf
  MemoryV1_1_4Lib|RedfishPocPkg/Library/RfishCS/edk2/Memory/v1_1_4/Lib.inf
  MemoryV1_2_0Lib|RedfishPocPkg/Library/RfishCS/edk2/Memory/v1_2_0/Lib.inf
  MemoryV1_2_1Lib|RedfishPocPkg/Library/RfishCS/edk2/Memory/v1_2_1/Lib.inf
  MemoryV1_2_2Lib|RedfishPocPkg/Library/RfishCS/edk2/Memory/v1_2_2/Lib.inf
  MemoryV1_2_3Lib|RedfishPocPkg/Library/RfishCS/edk2/Memory/v1_2_3/Lib.inf
  MemoryV1_3_0Lib|RedfishPocPkg/Library/RfishCS/edk2/Memory/v1_3_0/Lib.inf
  MemoryV1_3_1Lib|RedfishPocPkg/Library/RfishCS/edk2/Memory/v1_3_1/Lib.inf
  MemoryV1_3_2Lib|RedfishPocPkg/Library/RfishCS/edk2/Memory/v1_3_2/Lib.inf
  MemoryV1_3_3Lib|RedfishPocPkg/Library/RfishCS/edk2/Memory/v1_3_3/Lib.inf
  MemoryV1_4_0Lib|RedfishPocPkg/Library/RfishCS/edk2/Memory/v1_4_0/Lib.inf
  MemoryV1_4_1Lib|RedfishPocPkg/Library/RfishCS/edk2/Memory/v1_4_1/Lib.inf
  MemoryV1_4_2Lib|RedfishPocPkg/Library/RfishCS/edk2/Memory/v1_4_2/Lib.inf
  MemoryV1_4_3Lib|RedfishPocPkg/Library/RfishCS/edk2/Memory/v1_4_3/Lib.inf
  MemoryV1_5_0Lib|RedfishPocPkg/Library/RfishCS/edk2/Memory/v1_5_0/Lib.inf
  MemoryV1_5_1Lib|RedfishPocPkg/Library/RfishCS/edk2/Memory/v1_5_1/Lib.inf
  MemoryV1_5_2Lib|RedfishPocPkg/Library/RfishCS/edk2/Memory/v1_5_2/Lib.inf
  MemoryV1_6_0Lib|RedfishPocPkg/Library/RfishCS/edk2/Memory/v1_6_0/Lib.inf
  MemoryV1_6_1Lib|RedfishPocPkg/Library/RfishCS/edk2/Memory/v1_6_1/Lib.inf
  MemoryV1_7_0Lib|RedfishPocPkg/Library/RfishCS/edk2/Memory/v1_7_0/Lib.inf
  MemoryChunksV1_0_0Lib|RedfishPocPkg/Library/RfishCS/edk2/MemoryChunks/v1_0_0/Lib.inf
  MemoryChunksV1_0_1Lib|RedfishPocPkg/Library/RfishCS/edk2/MemoryChunks/v1_0_1/Lib.inf
  MemoryChunksV1_0_2Lib|RedfishPocPkg/Library/RfishCS/edk2/MemoryChunks/v1_0_2/Lib.inf
  MemoryChunksV1_0_3Lib|RedfishPocPkg/Library/RfishCS/edk2/MemoryChunks/v1_0_3/Lib.inf
  MemoryChunksV1_1_0Lib|RedfishPocPkg/Library/RfishCS/edk2/MemoryChunks/v1_1_0/Lib.inf
  MemoryChunksV1_1_1Lib|RedfishPocPkg/Library/RfishCS/edk2/MemoryChunks/v1_1_1/Lib.inf
  MemoryChunksV1_2_0Lib|RedfishPocPkg/Library/RfishCS/edk2/MemoryChunks/v1_2_0/Lib.inf
  MemoryChunksV1_2_1Lib|RedfishPocPkg/Library/RfishCS/edk2/MemoryChunks/v1_2_1/Lib.inf
  MemoryChunksV1_2_2Lib|RedfishPocPkg/Library/RfishCS/edk2/MemoryChunks/v1_2_2/Lib.inf
  MemoryChunksCollectionLib|RedfishPocPkg/Library/RfishCS/edk2/MemoryChunksCollection/Lib.inf
  MemoryCollectionLib|RedfishPocPkg/Library/RfishCS/edk2/MemoryCollection/Lib.inf
  MemoryDomainV1_0_0Lib|RedfishPocPkg/Library/RfishCS/edk2/MemoryDomain/v1_0_0/Lib.inf
  MemoryDomainV1_0_1Lib|RedfishPocPkg/Library/RfishCS/edk2/MemoryDomain/v1_0_1/Lib.inf
  MemoryDomainV1_0_2Lib|RedfishPocPkg/Library/RfishCS/edk2/MemoryDomain/v1_0_2/Lib.inf
  MemoryDomainV1_0_3Lib|RedfishPocPkg/Library/RfishCS/edk2/MemoryDomain/v1_0_3/Lib.inf
  MemoryDomainV1_1_0Lib|RedfishPocPkg/Library/RfishCS/edk2/MemoryDomain/v1_1_0/Lib.inf
  MemoryDomainV1_1_1Lib|RedfishPocPkg/Library/RfishCS/edk2/MemoryDomain/v1_1_1/Lib.inf
  MemoryDomainV1_1_2Lib|RedfishPocPkg/Library/RfishCS/edk2/MemoryDomain/v1_1_2/Lib.inf
  MemoryDomainV1_2_0Lib|RedfishPocPkg/Library/RfishCS/edk2/MemoryDomain/v1_2_0/Lib.inf
  MemoryDomainV1_2_1Lib|RedfishPocPkg/Library/RfishCS/edk2/MemoryDomain/v1_2_1/Lib.inf
  MemoryDomainCollectionLib|RedfishPocPkg/Library/RfishCS/edk2/MemoryDomainCollection/Lib.inf
  MemoryMetricsV1_0_0Lib|RedfishPocPkg/Library/RfishCS/edk2/MemoryMetrics/v1_0_0/Lib.inf
  MemoryMetricsV1_0_1Lib|RedfishPocPkg/Library/RfishCS/edk2/MemoryMetrics/v1_0_1/Lib.inf
  MemoryMetricsV1_0_2Lib|RedfishPocPkg/Library/RfishCS/edk2/MemoryMetrics/v1_0_2/Lib.inf
  MemoryMetricsV1_0_3Lib|RedfishPocPkg/Library/RfishCS/edk2/MemoryMetrics/v1_0_3/Lib.inf
  MemoryMetricsV1_0_4Lib|RedfishPocPkg/Library/RfishCS/edk2/MemoryMetrics/v1_0_4/Lib.inf
  MemoryMetricsV1_1_1Lib|RedfishPocPkg/Library/RfishCS/edk2/MemoryMetrics/v1_1_1/Lib.inf
  MemoryMetricsV1_1_2Lib|RedfishPocPkg/Library/RfishCS/edk2/MemoryMetrics/v1_1_2/Lib.inf
  MemoryMetricsV1_1_3Lib|RedfishPocPkg/Library/RfishCS/edk2/MemoryMetrics/v1_1_3/Lib.inf
  MemoryMetricsV1_1_4Lib|RedfishPocPkg/Library/RfishCS/edk2/MemoryMetrics/v1_1_4/Lib.inf
  MessageRegistryV1_0_0Lib|RedfishPocPkg/Library/RfishCS/edk2/MessageRegistry/v1_0_0/Lib.inf
  MessageRegistryV1_0_2Lib|RedfishPocPkg/Library/RfishCS/edk2/MessageRegistry/v1_0_2/Lib.inf
  MessageRegistryV1_0_3Lib|RedfishPocPkg/Library/RfishCS/edk2/MessageRegistry/v1_0_3/Lib.inf
  MessageRegistryV1_0_4Lib|RedfishPocPkg/Library/RfishCS/edk2/MessageRegistry/v1_0_4/Lib.inf
  MessageRegistryV1_0_5Lib|RedfishPocPkg/Library/RfishCS/edk2/MessageRegistry/v1_0_5/Lib.inf
  MessageRegistryV1_0_6Lib|RedfishPocPkg/Library/RfishCS/edk2/MessageRegistry/v1_0_6/Lib.inf
  MessageRegistryV1_1_0Lib|RedfishPocPkg/Library/RfishCS/edk2/MessageRegistry/v1_1_0/Lib.inf
  MessageRegistryV1_1_1Lib|RedfishPocPkg/Library/RfishCS/edk2/MessageRegistry/v1_1_1/Lib.inf
  MessageRegistryV1_1_2Lib|RedfishPocPkg/Library/RfishCS/edk2/MessageRegistry/v1_1_2/Lib.inf
  MessageRegistryV1_2_0Lib|RedfishPocPkg/Library/RfishCS/edk2/MessageRegistry/v1_2_0/Lib.inf
  MessageRegistryCollectionLib|RedfishPocPkg/Library/RfishCS/edk2/MessageRegistryCollection/Lib.inf
  MessageRegistryFileV1_0_0Lib|RedfishPocPkg/Library/RfishCS/edk2/MessageRegistryFile/v1_0_0/Lib.inf
  MessageRegistryFileV1_0_2Lib|RedfishPocPkg/Library/RfishCS/edk2/MessageRegistryFile/v1_0_2/Lib.inf
  MessageRegistryFileV1_0_3Lib|RedfishPocPkg/Library/RfishCS/edk2/MessageRegistryFile/v1_0_3/Lib.inf
  MessageRegistryFileV1_0_4Lib|RedfishPocPkg/Library/RfishCS/edk2/MessageRegistryFile/v1_0_4/Lib.inf
  MessageRegistryFileV1_0_5Lib|RedfishPocPkg/Library/RfishCS/edk2/MessageRegistryFile/v1_0_5/Lib.inf
  MessageRegistryFileV1_1_0Lib|RedfishPocPkg/Library/RfishCS/edk2/MessageRegistryFile/v1_1_0/Lib.inf
  MessageRegistryFileV1_1_1Lib|RedfishPocPkg/Library/RfishCS/edk2/MessageRegistryFile/v1_1_1/Lib.inf
  MessageRegistryFileCollectionLib|RedfishPocPkg/Library/RfishCS/edk2/MessageRegistryFileCollection/Lib.inf
  MetricDefinitionV1_0_0Lib|RedfishPocPkg/Library/RfishCS/edk2/MetricDefinition/v1_0_0/Lib.inf
  MetricDefinitionCollectionLib|RedfishPocPkg/Library/RfishCS/edk2/MetricDefinitionCollection/Lib.inf
  MetricReportV1_0_0Lib|RedfishPocPkg/Library/RfishCS/edk2/MetricReport/v1_0_0/Lib.inf
  MetricReportCollectionLib|RedfishPocPkg/Library/RfishCS/edk2/MetricReportCollection/Lib.inf
  MetricReportDefinitionV1_0_0Lib|RedfishPocPkg/Library/RfishCS/edk2/MetricReportDefinition/v1_0_0/Lib.inf
  MetricReportDefinitionCollectionLib|RedfishPocPkg/Library/RfishCS/edk2/MetricReportDefinitionCollection/Lib.inf
  NetworkAdapterV1_0_0Lib|RedfishPocPkg/Library/RfishCS/edk2/NetworkAdapter/v1_0_0/Lib.inf
  NetworkAdapterV1_0_1Lib|RedfishPocPkg/Library/RfishCS/edk2/NetworkAdapter/v1_0_1/Lib.inf
  NetworkAdapterV1_0_2Lib|RedfishPocPkg/Library/RfishCS/edk2/NetworkAdapter/v1_0_2/Lib.inf
  NetworkAdapterV1_1_0Lib|RedfishPocPkg/Library/RfishCS/edk2/NetworkAdapter/v1_1_0/Lib.inf
  NetworkAdapterV1_1_1Lib|RedfishPocPkg/Library/RfishCS/edk2/NetworkAdapter/v1_1_1/Lib.inf
  NetworkAdapterV1_2_0Lib|RedfishPocPkg/Library/RfishCS/edk2/NetworkAdapter/v1_2_0/Lib.inf
  NetworkAdapterCollectionLib|RedfishPocPkg/Library/RfishCS/edk2/NetworkAdapterCollection/Lib.inf
  NetworkDeviceFunctionV1_0_0Lib|RedfishPocPkg/Library/RfishCS/edk2/NetworkDeviceFunction/v1_0_0/Lib.inf
  NetworkDeviceFunctionV1_0_1Lib|RedfishPocPkg/Library/RfishCS/edk2/NetworkDeviceFunction/v1_0_1/Lib.inf
  NetworkDeviceFunctionV1_0_2Lib|RedfishPocPkg/Library/RfishCS/edk2/NetworkDeviceFunction/v1_0_2/Lib.inf
  NetworkDeviceFunctionV1_0_3Lib|RedfishPocPkg/Library/RfishCS/edk2/NetworkDeviceFunction/v1_0_3/Lib.inf
  NetworkDeviceFunctionV1_0_4Lib|RedfishPocPkg/Library/RfishCS/edk2/NetworkDeviceFunction/v1_0_4/Lib.inf
  NetworkDeviceFunctionV1_1_0Lib|RedfishPocPkg/Library/RfishCS/edk2/NetworkDeviceFunction/v1_1_0/Lib.inf
  NetworkDeviceFunctionV1_1_1Lib|RedfishPocPkg/Library/RfishCS/edk2/NetworkDeviceFunction/v1_1_1/Lib.inf
  NetworkDeviceFunctionV1_1_2Lib|RedfishPocPkg/Library/RfishCS/edk2/NetworkDeviceFunction/v1_1_2/Lib.inf
  NetworkDeviceFunctionV1_1_3Lib|RedfishPocPkg/Library/RfishCS/edk2/NetworkDeviceFunction/v1_1_3/Lib.inf
  NetworkDeviceFunctionV1_2_0Lib|RedfishPocPkg/Library/RfishCS/edk2/NetworkDeviceFunction/v1_2_0/Lib.inf
  NetworkDeviceFunctionV1_2_1Lib|RedfishPocPkg/Library/RfishCS/edk2/NetworkDeviceFunction/v1_2_1/Lib.inf
  NetworkDeviceFunctionV1_2_2Lib|RedfishPocPkg/Library/RfishCS/edk2/NetworkDeviceFunction/v1_2_2/Lib.inf
  NetworkDeviceFunctionV1_2_3Lib|RedfishPocPkg/Library/RfishCS/edk2/NetworkDeviceFunction/v1_2_3/Lib.inf
  NetworkDeviceFunctionV1_3_0Lib|RedfishPocPkg/Library/RfishCS/edk2/NetworkDeviceFunction/v1_3_0/Lib.inf
  NetworkDeviceFunctionV1_3_1Lib|RedfishPocPkg/Library/RfishCS/edk2/NetworkDeviceFunction/v1_3_1/Lib.inf
  NetworkDeviceFunctionCollectionLib|RedfishPocPkg/Library/RfishCS/edk2/NetworkDeviceFunctionCollection/Lib.inf
  NetworkInterfaceV1_0_0Lib|RedfishPocPkg/Library/RfishCS/edk2/NetworkInterface/v1_0_0/Lib.inf
  NetworkInterfaceV1_0_1Lib|RedfishPocPkg/Library/RfishCS/edk2/NetworkInterface/v1_0_1/Lib.inf
  NetworkInterfaceV1_0_2Lib|RedfishPocPkg/Library/RfishCS/edk2/NetworkInterface/v1_0_2/Lib.inf
  NetworkInterfaceV1_1_0Lib|RedfishPocPkg/Library/RfishCS/edk2/NetworkInterface/v1_1_0/Lib.inf
  NetworkInterfaceV1_1_1Lib|RedfishPocPkg/Library/RfishCS/edk2/NetworkInterface/v1_1_1/Lib.inf
  NetworkInterfaceCollectionLib|RedfishPocPkg/Library/RfishCS/edk2/NetworkInterfaceCollection/Lib.inf
  NetworkPortV1_0_0Lib|RedfishPocPkg/Library/RfishCS/edk2/NetworkPort/v1_0_0/Lib.inf
  NetworkPortV1_0_1Lib|RedfishPocPkg/Library/RfishCS/edk2/NetworkPort/v1_0_1/Lib.inf
  NetworkPortV1_0_2Lib|RedfishPocPkg/Library/RfishCS/edk2/NetworkPort/v1_0_2/Lib.inf
  NetworkPortV1_0_3Lib|RedfishPocPkg/Library/RfishCS/edk2/NetworkPort/v1_0_3/Lib.inf
  NetworkPortV1_1_0Lib|RedfishPocPkg/Library/RfishCS/edk2/NetworkPort/v1_1_0/Lib.inf
  NetworkPortV1_1_1Lib|RedfishPocPkg/Library/RfishCS/edk2/NetworkPort/v1_1_1/Lib.inf
  NetworkPortV1_1_2Lib|RedfishPocPkg/Library/RfishCS/edk2/NetworkPort/v1_1_2/Lib.inf
  NetworkPortV1_2_0Lib|RedfishPocPkg/Library/RfishCS/edk2/NetworkPort/v1_2_0/Lib.inf
  NetworkPortV1_2_1Lib|RedfishPocPkg/Library/RfishCS/edk2/NetworkPort/v1_2_1/Lib.inf
  NetworkPortCollectionLib|RedfishPocPkg/Library/RfishCS/edk2/NetworkPortCollection/Lib.inf
  PCIeDeviceV1_0_0Lib|RedfishPocPkg/Library/RfishCS/edk2/PCIeDevice/v1_0_0/Lib.inf
  PCIeDeviceV1_0_1Lib|RedfishPocPkg/Library/RfishCS/edk2/PCIeDevice/v1_0_1/Lib.inf
  PCIeDeviceV1_0_2Lib|RedfishPocPkg/Library/RfishCS/edk2/PCIeDevice/v1_0_2/Lib.inf
  PCIeDeviceV1_0_3Lib|RedfishPocPkg/Library/RfishCS/edk2/PCIeDevice/v1_0_3/Lib.inf
  PCIeDeviceV1_1_0Lib|RedfishPocPkg/Library/RfishCS/edk2/PCIeDevice/v1_1_0/Lib.inf
  PCIeDeviceV1_1_1Lib|RedfishPocPkg/Library/RfishCS/edk2/PCIeDevice/v1_1_1/Lib.inf
  PCIeDeviceV1_2_0Lib|RedfishPocPkg/Library/RfishCS/edk2/PCIeDevice/v1_2_0/Lib.inf
  PCIeDeviceV1_2_1Lib|RedfishPocPkg/Library/RfishCS/edk2/PCIeDevice/v1_2_1/Lib.inf
  PCIeDeviceV1_3_0Lib|RedfishPocPkg/Library/RfishCS/edk2/PCIeDevice/v1_3_0/Lib.inf
  PCIeFunctionV1_0_0Lib|RedfishPocPkg/Library/RfishCS/edk2/PCIeFunction/v1_0_0/Lib.inf
  PCIeFunctionV1_0_1Lib|RedfishPocPkg/Library/RfishCS/edk2/PCIeFunction/v1_0_1/Lib.inf
  PCIeFunctionV1_0_2Lib|RedfishPocPkg/Library/RfishCS/edk2/PCIeFunction/v1_0_2/Lib.inf
  PCIeFunctionV1_0_3Lib|RedfishPocPkg/Library/RfishCS/edk2/PCIeFunction/v1_0_3/Lib.inf
  PCIeFunctionV1_0_4Lib|RedfishPocPkg/Library/RfishCS/edk2/PCIeFunction/v1_0_4/Lib.inf
  PCIeFunctionV1_1_0Lib|RedfishPocPkg/Library/RfishCS/edk2/PCIeFunction/v1_1_0/Lib.inf
  PCIeFunctionV1_1_1Lib|RedfishPocPkg/Library/RfishCS/edk2/PCIeFunction/v1_1_1/Lib.inf
  PCIeFunctionV1_1_2Lib|RedfishPocPkg/Library/RfishCS/edk2/PCIeFunction/v1_1_2/Lib.inf
  PCIeFunctionV1_2_0Lib|RedfishPocPkg/Library/RfishCS/edk2/PCIeFunction/v1_2_0/Lib.inf
  PCIeFunctionV1_2_1Lib|RedfishPocPkg/Library/RfishCS/edk2/PCIeFunction/v1_2_1/Lib.inf
  PCIeSlotsV1_0_0Lib|RedfishPocPkg/Library/RfishCS/edk2/PCIeSlots/v1_0_0/Lib.inf
  PortV1_0_0Lib|RedfishPocPkg/Library/RfishCS/edk2/Port/v1_0_0/Lib.inf
  PortV1_0_1Lib|RedfishPocPkg/Library/RfishCS/edk2/Port/v1_0_1/Lib.inf
  PortV1_0_2Lib|RedfishPocPkg/Library/RfishCS/edk2/Port/v1_0_2/Lib.inf
  PortV1_0_3Lib|RedfishPocPkg/Library/RfishCS/edk2/Port/v1_0_3/Lib.inf
  PortV1_0_4Lib|RedfishPocPkg/Library/RfishCS/edk2/Port/v1_0_4/Lib.inf
  PortV1_1_0Lib|RedfishPocPkg/Library/RfishCS/edk2/Port/v1_1_0/Lib.inf
  PortV1_1_1Lib|RedfishPocPkg/Library/RfishCS/edk2/Port/v1_1_1/Lib.inf
  PortCollectionLib|RedfishPocPkg/Library/RfishCS/edk2/PortCollection/Lib.inf
  PowerV1_0_0Lib|RedfishPocPkg/Library/RfishCS/edk2/Power/v1_0_0/Lib.inf
  PowerV1_0_1Lib|RedfishPocPkg/Library/RfishCS/edk2/Power/v1_0_1/Lib.inf
  PowerV1_0_2Lib|RedfishPocPkg/Library/RfishCS/edk2/Power/v1_0_2/Lib.inf
  PowerV1_0_3Lib|RedfishPocPkg/Library/RfishCS/edk2/Power/v1_0_3/Lib.inf
  PowerV1_0_4Lib|RedfishPocPkg/Library/RfishCS/edk2/Power/v1_0_4/Lib.inf
  PowerV1_0_5Lib|RedfishPocPkg/Library/RfishCS/edk2/Power/v1_0_5/Lib.inf
  PowerV1_0_6Lib|RedfishPocPkg/Library/RfishCS/edk2/Power/v1_0_6/Lib.inf
  PowerV1_0_7Lib|RedfishPocPkg/Library/RfishCS/edk2/Power/v1_0_7/Lib.inf
  PowerV1_0_8Lib|RedfishPocPkg/Library/RfishCS/edk2/Power/v1_0_8/Lib.inf
  PowerV1_1_0Lib|RedfishPocPkg/Library/RfishCS/edk2/Power/v1_1_0/Lib.inf
  PowerV1_1_1Lib|RedfishPocPkg/Library/RfishCS/edk2/Power/v1_1_1/Lib.inf
  PowerV1_1_2Lib|RedfishPocPkg/Library/RfishCS/edk2/Power/v1_1_2/Lib.inf
  PowerV1_1_3Lib|RedfishPocPkg/Library/RfishCS/edk2/Power/v1_1_3/Lib.inf
  PowerV1_1_4Lib|RedfishPocPkg/Library/RfishCS/edk2/Power/v1_1_4/Lib.inf
  PowerV1_1_5Lib|RedfishPocPkg/Library/RfishCS/edk2/Power/v1_1_5/Lib.inf
  PowerV1_1_6Lib|RedfishPocPkg/Library/RfishCS/edk2/Power/v1_1_6/Lib.inf
  PowerV1_2_0Lib|RedfishPocPkg/Library/RfishCS/edk2/Power/v1_2_0/Lib.inf
  PowerV1_2_1Lib|RedfishPocPkg/Library/RfishCS/edk2/Power/v1_2_1/Lib.inf
  PowerV1_2_2Lib|RedfishPocPkg/Library/RfishCS/edk2/Power/v1_2_2/Lib.inf
  PowerV1_2_3Lib|RedfishPocPkg/Library/RfishCS/edk2/Power/v1_2_3/Lib.inf
  PowerV1_2_4Lib|RedfishPocPkg/Library/RfishCS/edk2/Power/v1_2_4/Lib.inf
  PowerV1_2_5Lib|RedfishPocPkg/Library/RfishCS/edk2/Power/v1_2_5/Lib.inf
  PowerV1_2_6Lib|RedfishPocPkg/Library/RfishCS/edk2/Power/v1_2_6/Lib.inf
  PowerV1_3_0Lib|RedfishPocPkg/Library/RfishCS/edk2/Power/v1_3_0/Lib.inf
  PowerV1_3_1Lib|RedfishPocPkg/Library/RfishCS/edk2/Power/v1_3_1/Lib.inf
  PowerV1_3_2Lib|RedfishPocPkg/Library/RfishCS/edk2/Power/v1_3_2/Lib.inf
  PowerV1_3_3Lib|RedfishPocPkg/Library/RfishCS/edk2/Power/v1_3_3/Lib.inf
  PowerV1_3_4Lib|RedfishPocPkg/Library/RfishCS/edk2/Power/v1_3_4/Lib.inf
  PowerV1_4_0Lib|RedfishPocPkg/Library/RfishCS/edk2/Power/v1_4_0/Lib.inf
  PowerV1_4_1Lib|RedfishPocPkg/Library/RfishCS/edk2/Power/v1_4_1/Lib.inf
  PowerV1_4_2Lib|RedfishPocPkg/Library/RfishCS/edk2/Power/v1_4_2/Lib.inf
  PowerV1_4_3Lib|RedfishPocPkg/Library/RfishCS/edk2/Power/v1_4_3/Lib.inf
  PowerV1_5_0Lib|RedfishPocPkg/Library/RfishCS/edk2/Power/v1_5_0/Lib.inf
  PowerV1_5_1Lib|RedfishPocPkg/Library/RfishCS/edk2/Power/v1_5_1/Lib.inf
  PowerV1_5_2Lib|RedfishPocPkg/Library/RfishCS/edk2/Power/v1_5_2/Lib.inf
  PrivilegeRegistryV1_0_0Lib|RedfishPocPkg/Library/RfishCS/edk2/PrivilegeRegistry/v1_0_0/Lib.inf
  PrivilegeRegistryV1_0_1Lib|RedfishPocPkg/Library/RfishCS/edk2/PrivilegeRegistry/v1_0_1/Lib.inf
  PrivilegeRegistryV1_0_2Lib|RedfishPocPkg/Library/RfishCS/edk2/PrivilegeRegistry/v1_0_2/Lib.inf
  PrivilegeRegistryV1_0_3Lib|RedfishPocPkg/Library/RfishCS/edk2/PrivilegeRegistry/v1_0_3/Lib.inf
  PrivilegeRegistryV1_1_0Lib|RedfishPocPkg/Library/RfishCS/edk2/PrivilegeRegistry/v1_1_0/Lib.inf
  PrivilegeRegistryV1_1_1Lib|RedfishPocPkg/Library/RfishCS/edk2/PrivilegeRegistry/v1_1_1/Lib.inf
  PrivilegeRegistryV1_1_2Lib|RedfishPocPkg/Library/RfishCS/edk2/PrivilegeRegistry/v1_1_2/Lib.inf
  ProcessorV1_0_0Lib|RedfishPocPkg/Library/RfishCS/edk2/Processor/v1_0_0/Lib.inf
  ProcessorV1_0_2Lib|RedfishPocPkg/Library/RfishCS/edk2/Processor/v1_0_2/Lib.inf
  ProcessorV1_0_3Lib|RedfishPocPkg/Library/RfishCS/edk2/Processor/v1_0_3/Lib.inf
  ProcessorV1_0_4Lib|RedfishPocPkg/Library/RfishCS/edk2/Processor/v1_0_4/Lib.inf
  ProcessorV1_0_5Lib|RedfishPocPkg/Library/RfishCS/edk2/Processor/v1_0_5/Lib.inf
  ProcessorV1_0_6Lib|RedfishPocPkg/Library/RfishCS/edk2/Processor/v1_0_6/Lib.inf
  ProcessorV1_1_0Lib|RedfishPocPkg/Library/RfishCS/edk2/Processor/v1_1_0/Lib.inf
  ProcessorV1_1_1Lib|RedfishPocPkg/Library/RfishCS/edk2/Processor/v1_1_1/Lib.inf
  ProcessorV1_1_2Lib|RedfishPocPkg/Library/RfishCS/edk2/Processor/v1_1_2/Lib.inf
  ProcessorV1_2_0Lib|RedfishPocPkg/Library/RfishCS/edk2/Processor/v1_2_0/Lib.inf
  ProcessorV1_2_1Lib|RedfishPocPkg/Library/RfishCS/edk2/Processor/v1_2_1/Lib.inf
  ProcessorV1_2_2Lib|RedfishPocPkg/Library/RfishCS/edk2/Processor/v1_2_2/Lib.inf
  ProcessorV1_3_0Lib|RedfishPocPkg/Library/RfishCS/edk2/Processor/v1_3_0/Lib.inf
  ProcessorV1_3_1Lib|RedfishPocPkg/Library/RfishCS/edk2/Processor/v1_3_1/Lib.inf
  ProcessorV1_3_2Lib|RedfishPocPkg/Library/RfishCS/edk2/Processor/v1_3_2/Lib.inf
  ProcessorV1_4_0Lib|RedfishPocPkg/Library/RfishCS/edk2/Processor/v1_4_0/Lib.inf
  ProcessorCollectionLib|RedfishPocPkg/Library/RfishCS/edk2/ProcessorCollection/Lib.inf
  ResourceBlockV1_0_0Lib|RedfishPocPkg/Library/RfishCS/edk2/ResourceBlock/v1_0_0/Lib.inf
  ResourceBlockV1_0_1Lib|RedfishPocPkg/Library/RfishCS/edk2/ResourceBlock/v1_0_1/Lib.inf
  ResourceBlockV1_0_2Lib|RedfishPocPkg/Library/RfishCS/edk2/ResourceBlock/v1_0_2/Lib.inf
  ResourceBlockV1_1_0Lib|RedfishPocPkg/Library/RfishCS/edk2/ResourceBlock/v1_1_0/Lib.inf
  ResourceBlockV1_1_1Lib|RedfishPocPkg/Library/RfishCS/edk2/ResourceBlock/v1_1_1/Lib.inf
  ResourceBlockV1_1_2Lib|RedfishPocPkg/Library/RfishCS/edk2/ResourceBlock/v1_1_2/Lib.inf
  ResourceBlockV1_2_0Lib|RedfishPocPkg/Library/RfishCS/edk2/ResourceBlock/v1_2_0/Lib.inf
  ResourceBlockV1_2_1Lib|RedfishPocPkg/Library/RfishCS/edk2/ResourceBlock/v1_2_1/Lib.inf
  ResourceBlockCollectionLib|RedfishPocPkg/Library/RfishCS/edk2/ResourceBlockCollection/Lib.inf
  RoleV1_0_0Lib|RedfishPocPkg/Library/RfishCS/edk2/Role/v1_0_0/Lib.inf
  RoleV1_0_2Lib|RedfishPocPkg/Library/RfishCS/edk2/Role/v1_0_2/Lib.inf
  RoleV1_0_3Lib|RedfishPocPkg/Library/RfishCS/edk2/Role/v1_0_3/Lib.inf
  RoleV1_0_4Lib|RedfishPocPkg/Library/RfishCS/edk2/Role/v1_0_4/Lib.inf
  RoleV1_1_0Lib|RedfishPocPkg/Library/RfishCS/edk2/Role/v1_1_0/Lib.inf
  RoleV1_1_1Lib|RedfishPocPkg/Library/RfishCS/edk2/Role/v1_1_1/Lib.inf
  RoleV1_1_2Lib|RedfishPocPkg/Library/RfishCS/edk2/Role/v1_1_2/Lib.inf
  RoleV1_2_0Lib|RedfishPocPkg/Library/RfishCS/edk2/Role/v1_2_0/Lib.inf
  RoleV1_2_1Lib|RedfishPocPkg/Library/RfishCS/edk2/Role/v1_2_1/Lib.inf
  RoleV1_2_2Lib|RedfishPocPkg/Library/RfishCS/edk2/Role/v1_2_2/Lib.inf
  RoleCollectionLib|RedfishPocPkg/Library/RfishCS/edk2/RoleCollection/Lib.inf
  SecureBootV1_0_0Lib|RedfishPocPkg/Library/RfishCS/edk2/SecureBoot/v1_0_0/Lib.inf
  SecureBootV1_0_1Lib|RedfishPocPkg/Library/RfishCS/edk2/SecureBoot/v1_0_1/Lib.inf
  SecureBootV1_0_2Lib|RedfishPocPkg/Library/RfishCS/edk2/SecureBoot/v1_0_2/Lib.inf
  SecureBootV1_0_3Lib|RedfishPocPkg/Library/RfishCS/edk2/SecureBoot/v1_0_3/Lib.inf
  SecureBootV1_0_4Lib|RedfishPocPkg/Library/RfishCS/edk2/SecureBoot/v1_0_4/Lib.inf
  SerialInterfaceV1_0_0Lib|RedfishPocPkg/Library/RfishCS/edk2/SerialInterface/v1_0_0/Lib.inf
  SerialInterfaceV1_0_2Lib|RedfishPocPkg/Library/RfishCS/edk2/SerialInterface/v1_0_2/Lib.inf
  SerialInterfaceV1_0_3Lib|RedfishPocPkg/Library/RfishCS/edk2/SerialInterface/v1_0_3/Lib.inf
  SerialInterfaceV1_0_4Lib|RedfishPocPkg/Library/RfishCS/edk2/SerialInterface/v1_0_4/Lib.inf
  SerialInterfaceV1_0_5Lib|RedfishPocPkg/Library/RfishCS/edk2/SerialInterface/v1_0_5/Lib.inf
  SerialInterfaceV1_0_6Lib|RedfishPocPkg/Library/RfishCS/edk2/SerialInterface/v1_0_6/Lib.inf
  SerialInterfaceV1_1_0Lib|RedfishPocPkg/Library/RfishCS/edk2/SerialInterface/v1_1_0/Lib.inf
  SerialInterfaceV1_1_1Lib|RedfishPocPkg/Library/RfishCS/edk2/SerialInterface/v1_1_1/Lib.inf
  SerialInterfaceV1_1_2Lib|RedfishPocPkg/Library/RfishCS/edk2/SerialInterface/v1_1_2/Lib.inf
  SerialInterfaceV1_1_3Lib|RedfishPocPkg/Library/RfishCS/edk2/SerialInterface/v1_1_3/Lib.inf
  SerialInterfaceCollectionLib|RedfishPocPkg/Library/RfishCS/edk2/SerialInterfaceCollection/Lib.inf
  ServiceRootV1_0_0Lib|RedfishPocPkg/Library/RfishCS/edk2/ServiceRoot/v1_0_0/Lib.inf
  ServiceRootV1_0_2Lib|RedfishPocPkg/Library/RfishCS/edk2/ServiceRoot/v1_0_2/Lib.inf
  ServiceRootV1_0_3Lib|RedfishPocPkg/Library/RfishCS/edk2/ServiceRoot/v1_0_3/Lib.inf
  ServiceRootV1_0_4Lib|RedfishPocPkg/Library/RfishCS/edk2/ServiceRoot/v1_0_4/Lib.inf
  ServiceRootV1_0_5Lib|RedfishPocPkg/Library/RfishCS/edk2/ServiceRoot/v1_0_5/Lib.inf
  ServiceRootV1_0_6Lib|RedfishPocPkg/Library/RfishCS/edk2/ServiceRoot/v1_0_6/Lib.inf
  ServiceRootV1_0_7Lib|RedfishPocPkg/Library/RfishCS/edk2/ServiceRoot/v1_0_7/Lib.inf
  ServiceRootV1_1_0Lib|RedfishPocPkg/Library/RfishCS/edk2/ServiceRoot/v1_1_0/Lib.inf
  ServiceRootV1_1_1Lib|RedfishPocPkg/Library/RfishCS/edk2/ServiceRoot/v1_1_1/Lib.inf
  ServiceRootV1_1_2Lib|RedfishPocPkg/Library/RfishCS/edk2/ServiceRoot/v1_1_2/Lib.inf
  ServiceRootV1_1_3Lib|RedfishPocPkg/Library/RfishCS/edk2/ServiceRoot/v1_1_3/Lib.inf
  ServiceRootV1_1_4Lib|RedfishPocPkg/Library/RfishCS/edk2/ServiceRoot/v1_1_4/Lib.inf
  ServiceRootV1_2_0Lib|RedfishPocPkg/Library/RfishCS/edk2/ServiceRoot/v1_2_0/Lib.inf
  ServiceRootV1_2_1Lib|RedfishPocPkg/Library/RfishCS/edk2/ServiceRoot/v1_2_1/Lib.inf
  ServiceRootV1_2_2Lib|RedfishPocPkg/Library/RfishCS/edk2/ServiceRoot/v1_2_2/Lib.inf
  ServiceRootV1_3_0Lib|RedfishPocPkg/Library/RfishCS/edk2/ServiceRoot/v1_3_0/Lib.inf
  ServiceRootV1_3_1Lib|RedfishPocPkg/Library/RfishCS/edk2/ServiceRoot/v1_3_1/Lib.inf
  ServiceRootV1_3_2Lib|RedfishPocPkg/Library/RfishCS/edk2/ServiceRoot/v1_3_2/Lib.inf
  ServiceRootV1_3_3Lib|RedfishPocPkg/Library/RfishCS/edk2/ServiceRoot/v1_3_3/Lib.inf
  ServiceRootV1_4_0Lib|RedfishPocPkg/Library/RfishCS/edk2/ServiceRoot/v1_4_0/Lib.inf
  ServiceRootV1_4_1Lib|RedfishPocPkg/Library/RfishCS/edk2/ServiceRoot/v1_4_1/Lib.inf
  ServiceRootV1_5_0Lib|RedfishPocPkg/Library/RfishCS/edk2/ServiceRoot/v1_5_0/Lib.inf
  SessionV1_0_0Lib|RedfishPocPkg/Library/RfishCS/edk2/Session/v1_0_0/Lib.inf
  SessionV1_0_2Lib|RedfishPocPkg/Library/RfishCS/edk2/Session/v1_0_2/Lib.inf
  SessionV1_0_3Lib|RedfishPocPkg/Library/RfishCS/edk2/Session/v1_0_3/Lib.inf
  SessionV1_0_4Lib|RedfishPocPkg/Library/RfishCS/edk2/Session/v1_0_4/Lib.inf
  SessionV1_1_0Lib|RedfishPocPkg/Library/RfishCS/edk2/Session/v1_1_0/Lib.inf
  SessionV1_1_1Lib|RedfishPocPkg/Library/RfishCS/edk2/Session/v1_1_1/Lib.inf
  SessionCollectionLib|RedfishPocPkg/Library/RfishCS/edk2/SessionCollection/Lib.inf
  SessionServiceV1_0_0Lib|RedfishPocPkg/Library/RfishCS/edk2/SessionService/v1_0_0/Lib.inf
  SessionServiceV1_0_2Lib|RedfishPocPkg/Library/RfishCS/edk2/SessionService/v1_0_2/Lib.inf
  SessionServiceV1_0_3Lib|RedfishPocPkg/Library/RfishCS/edk2/SessionService/v1_0_3/Lib.inf
  SessionServiceV1_0_4Lib|RedfishPocPkg/Library/RfishCS/edk2/SessionService/v1_0_4/Lib.inf
  SessionServiceV1_0_5Lib|RedfishPocPkg/Library/RfishCS/edk2/SessionService/v1_0_5/Lib.inf
  SessionServiceV1_1_0Lib|RedfishPocPkg/Library/RfishCS/edk2/SessionService/v1_1_0/Lib.inf
  SessionServiceV1_1_1Lib|RedfishPocPkg/Library/RfishCS/edk2/SessionService/v1_1_1/Lib.inf
  SessionServiceV1_1_2Lib|RedfishPocPkg/Library/RfishCS/edk2/SessionService/v1_1_2/Lib.inf
  SessionServiceV1_1_3Lib|RedfishPocPkg/Library/RfishCS/edk2/SessionService/v1_1_3/Lib.inf
  SessionServiceV1_1_4Lib|RedfishPocPkg/Library/RfishCS/edk2/SessionService/v1_1_4/Lib.inf
  SimpleStorageV1_0_0Lib|RedfishPocPkg/Library/RfishCS/edk2/SimpleStorage/v1_0_0/Lib.inf
  SimpleStorageV1_0_2Lib|RedfishPocPkg/Library/RfishCS/edk2/SimpleStorage/v1_0_2/Lib.inf
  SimpleStorageV1_0_3Lib|RedfishPocPkg/Library/RfishCS/edk2/SimpleStorage/v1_0_3/Lib.inf
  SimpleStorageV1_0_4Lib|RedfishPocPkg/Library/RfishCS/edk2/SimpleStorage/v1_0_4/Lib.inf
  SimpleStorageV1_0_5Lib|RedfishPocPkg/Library/RfishCS/edk2/SimpleStorage/v1_0_5/Lib.inf
  SimpleStorageV1_1_0Lib|RedfishPocPkg/Library/RfishCS/edk2/SimpleStorage/v1_1_0/Lib.inf
  SimpleStorageV1_1_1Lib|RedfishPocPkg/Library/RfishCS/edk2/SimpleStorage/v1_1_1/Lib.inf
  SimpleStorageV1_1_2Lib|RedfishPocPkg/Library/RfishCS/edk2/SimpleStorage/v1_1_2/Lib.inf
  SimpleStorageV1_1_3Lib|RedfishPocPkg/Library/RfishCS/edk2/SimpleStorage/v1_1_3/Lib.inf
  SimpleStorageV1_2_0Lib|RedfishPocPkg/Library/RfishCS/edk2/SimpleStorage/v1_2_0/Lib.inf
  SimpleStorageV1_2_1Lib|RedfishPocPkg/Library/RfishCS/edk2/SimpleStorage/v1_2_1/Lib.inf
  SimpleStorageCollectionLib|RedfishPocPkg/Library/RfishCS/edk2/SimpleStorageCollection/Lib.inf
  SoftwareInventoryV1_0_0Lib|RedfishPocPkg/Library/RfishCS/edk2/SoftwareInventory/v1_0_0/Lib.inf
  SoftwareInventoryV1_0_1Lib|RedfishPocPkg/Library/RfishCS/edk2/SoftwareInventory/v1_0_1/Lib.inf
  SoftwareInventoryV1_0_2Lib|RedfishPocPkg/Library/RfishCS/edk2/SoftwareInventory/v1_0_2/Lib.inf
  SoftwareInventoryV1_0_3Lib|RedfishPocPkg/Library/RfishCS/edk2/SoftwareInventory/v1_0_3/Lib.inf
  SoftwareInventoryV1_1_0Lib|RedfishPocPkg/Library/RfishCS/edk2/SoftwareInventory/v1_1_0/Lib.inf
  SoftwareInventoryV1_1_1Lib|RedfishPocPkg/Library/RfishCS/edk2/SoftwareInventory/v1_1_1/Lib.inf
  SoftwareInventoryV1_1_2Lib|RedfishPocPkg/Library/RfishCS/edk2/SoftwareInventory/v1_1_2/Lib.inf
  SoftwareInventoryV1_2_0Lib|RedfishPocPkg/Library/RfishCS/edk2/SoftwareInventory/v1_2_0/Lib.inf
  SoftwareInventoryV1_2_1Lib|RedfishPocPkg/Library/RfishCS/edk2/SoftwareInventory/v1_2_1/Lib.inf
  SoftwareInventoryCollectionLib|RedfishPocPkg/Library/RfishCS/edk2/SoftwareInventoryCollection/Lib.inf
  StorageV1_0_1Lib|RedfishPocPkg/Library/RfishCS/edk2/Storage/v1_0_1/Lib.inf
  StorageV1_0_2Lib|RedfishPocPkg/Library/RfishCS/edk2/Storage/v1_0_2/Lib.inf
  StorageV1_0_3Lib|RedfishPocPkg/Library/RfishCS/edk2/Storage/v1_0_3/Lib.inf
  StorageV1_0_4Lib|RedfishPocPkg/Library/RfishCS/edk2/Storage/v1_0_4/Lib.inf
  StorageV1_0_5Lib|RedfishPocPkg/Library/RfishCS/edk2/Storage/v1_0_5/Lib.inf
  StorageV1_0_6Lib|RedfishPocPkg/Library/RfishCS/edk2/Storage/v1_0_6/Lib.inf
  StorageV1_1_1Lib|RedfishPocPkg/Library/RfishCS/edk2/Storage/v1_1_1/Lib.inf
  StorageV1_1_2Lib|RedfishPocPkg/Library/RfishCS/edk2/Storage/v1_1_2/Lib.inf
  StorageV1_1_3Lib|RedfishPocPkg/Library/RfishCS/edk2/Storage/v1_1_3/Lib.inf
  StorageV1_1_4Lib|RedfishPocPkg/Library/RfishCS/edk2/Storage/v1_1_4/Lib.inf
  StorageV1_1_5Lib|RedfishPocPkg/Library/RfishCS/edk2/Storage/v1_1_5/Lib.inf
  StorageV1_2_0Lib|RedfishPocPkg/Library/RfishCS/edk2/Storage/v1_2_0/Lib.inf
  StorageV1_2_1Lib|RedfishPocPkg/Library/RfishCS/edk2/Storage/v1_2_1/Lib.inf
  StorageV1_2_2Lib|RedfishPocPkg/Library/RfishCS/edk2/Storage/v1_2_2/Lib.inf
  StorageV1_2_3Lib|RedfishPocPkg/Library/RfishCS/edk2/Storage/v1_2_3/Lib.inf
  StorageV1_3_0Lib|RedfishPocPkg/Library/RfishCS/edk2/Storage/v1_3_0/Lib.inf
  StorageV1_3_1Lib|RedfishPocPkg/Library/RfishCS/edk2/Storage/v1_3_1/Lib.inf
  StorageV1_3_2Lib|RedfishPocPkg/Library/RfishCS/edk2/Storage/v1_3_2/Lib.inf
  StorageV1_3_3Lib|RedfishPocPkg/Library/RfishCS/edk2/Storage/v1_3_3/Lib.inf
  StorageV1_4_0Lib|RedfishPocPkg/Library/RfishCS/edk2/Storage/v1_4_0/Lib.inf
  StorageV1_4_1Lib|RedfishPocPkg/Library/RfishCS/edk2/Storage/v1_4_1/Lib.inf
  StorageV1_4_2Lib|RedfishPocPkg/Library/RfishCS/edk2/Storage/v1_4_2/Lib.inf
  StorageV1_5_0Lib|RedfishPocPkg/Library/RfishCS/edk2/Storage/v1_5_0/Lib.inf
  StorageV1_5_1Lib|RedfishPocPkg/Library/RfishCS/edk2/Storage/v1_5_1/Lib.inf
  StorageCollectionLib|RedfishPocPkg/Library/RfishCS/edk2/StorageCollection/Lib.inf
  SwitchV1_0_0Lib|RedfishPocPkg/Library/RfishCS/edk2/Switch/v1_0_0/Lib.inf
  SwitchV1_0_1Lib|RedfishPocPkg/Library/RfishCS/edk2/Switch/v1_0_1/Lib.inf
  SwitchV1_0_2Lib|RedfishPocPkg/Library/RfishCS/edk2/Switch/v1_0_2/Lib.inf
  SwitchV1_0_3Lib|RedfishPocPkg/Library/RfishCS/edk2/Switch/v1_0_3/Lib.inf
  SwitchV1_0_4Lib|RedfishPocPkg/Library/RfishCS/edk2/Switch/v1_0_4/Lib.inf
  SwitchV1_1_0Lib|RedfishPocPkg/Library/RfishCS/edk2/Switch/v1_1_0/Lib.inf
  SwitchV1_1_1Lib|RedfishPocPkg/Library/RfishCS/edk2/Switch/v1_1_1/Lib.inf
  SwitchCollectionLib|RedfishPocPkg/Library/RfishCS/edk2/SwitchCollection/Lib.inf
  TaskV1_0_0Lib|RedfishPocPkg/Library/RfishCS/edk2/Task/v1_0_0/Lib.inf
  TaskV1_0_2Lib|RedfishPocPkg/Library/RfishCS/edk2/Task/v1_0_2/Lib.inf
  TaskV1_0_3Lib|RedfishPocPkg/Library/RfishCS/edk2/Task/v1_0_3/Lib.inf
  TaskV1_0_4Lib|RedfishPocPkg/Library/RfishCS/edk2/Task/v1_0_4/Lib.inf
  TaskV1_0_5Lib|RedfishPocPkg/Library/RfishCS/edk2/Task/v1_0_5/Lib.inf
  TaskV1_0_6Lib|RedfishPocPkg/Library/RfishCS/edk2/Task/v1_0_6/Lib.inf
  TaskV1_1_0Lib|RedfishPocPkg/Library/RfishCS/edk2/Task/v1_1_0/Lib.inf
  TaskV1_1_1Lib|RedfishPocPkg/Library/RfishCS/edk2/Task/v1_1_1/Lib.inf
  TaskV1_1_2Lib|RedfishPocPkg/Library/RfishCS/edk2/Task/v1_1_2/Lib.inf
  TaskV1_1_3Lib|RedfishPocPkg/Library/RfishCS/edk2/Task/v1_1_3/Lib.inf
  TaskV1_2_0Lib|RedfishPocPkg/Library/RfishCS/edk2/Task/v1_2_0/Lib.inf
  TaskV1_2_1Lib|RedfishPocPkg/Library/RfishCS/edk2/Task/v1_2_1/Lib.inf
  TaskV1_2_2Lib|RedfishPocPkg/Library/RfishCS/edk2/Task/v1_2_2/Lib.inf
  TaskV1_3_0Lib|RedfishPocPkg/Library/RfishCS/edk2/Task/v1_3_0/Lib.inf
  TaskV1_3_1Lib|RedfishPocPkg/Library/RfishCS/edk2/Task/v1_3_1/Lib.inf
  TaskCollectionLib|RedfishPocPkg/Library/RfishCS/edk2/TaskCollection/Lib.inf
  TaskServiceV1_0_0Lib|RedfishPocPkg/Library/RfishCS/edk2/TaskService/v1_0_0/Lib.inf
  TaskServiceV1_0_2Lib|RedfishPocPkg/Library/RfishCS/edk2/TaskService/v1_0_2/Lib.inf
  TaskServiceV1_0_3Lib|RedfishPocPkg/Library/RfishCS/edk2/TaskService/v1_0_3/Lib.inf
  TaskServiceV1_0_4Lib|RedfishPocPkg/Library/RfishCS/edk2/TaskService/v1_0_4/Lib.inf
  TaskServiceV1_0_5Lib|RedfishPocPkg/Library/RfishCS/edk2/TaskService/v1_0_5/Lib.inf
  TaskServiceV1_1_0Lib|RedfishPocPkg/Library/RfishCS/edk2/TaskService/v1_1_0/Lib.inf
  TaskServiceV1_1_1Lib|RedfishPocPkg/Library/RfishCS/edk2/TaskService/v1_1_1/Lib.inf
  TaskServiceV1_1_2Lib|RedfishPocPkg/Library/RfishCS/edk2/TaskService/v1_1_2/Lib.inf
  TelemetryServiceV1_0_0Lib|RedfishPocPkg/Library/RfishCS/edk2/TelemetryService/v1_0_0/Lib.inf
  ThermalV1_0_0Lib|RedfishPocPkg/Library/RfishCS/edk2/Thermal/v1_0_0/Lib.inf
  ThermalV1_0_1Lib|RedfishPocPkg/Library/RfishCS/edk2/Thermal/v1_0_1/Lib.inf
  ThermalV1_0_2Lib|RedfishPocPkg/Library/RfishCS/edk2/Thermal/v1_0_2/Lib.inf
  ThermalV1_0_3Lib|RedfishPocPkg/Library/RfishCS/edk2/Thermal/v1_0_3/Lib.inf
  ThermalV1_0_4Lib|RedfishPocPkg/Library/RfishCS/edk2/Thermal/v1_0_4/Lib.inf
  ThermalV1_0_5Lib|RedfishPocPkg/Library/RfishCS/edk2/Thermal/v1_0_5/Lib.inf
  ThermalV1_0_6Lib|RedfishPocPkg/Library/RfishCS/edk2/Thermal/v1_0_6/Lib.inf
  ThermalV1_0_7Lib|RedfishPocPkg/Library/RfishCS/edk2/Thermal/v1_0_7/Lib.inf
  ThermalV1_0_8Lib|RedfishPocPkg/Library/RfishCS/edk2/Thermal/v1_0_8/Lib.inf
  ThermalV1_1_0Lib|RedfishPocPkg/Library/RfishCS/edk2/Thermal/v1_1_0/Lib.inf
  ThermalV1_1_1Lib|RedfishPocPkg/Library/RfishCS/edk2/Thermal/v1_1_1/Lib.inf
  ThermalV1_1_2Lib|RedfishPocPkg/Library/RfishCS/edk2/Thermal/v1_1_2/Lib.inf
  ThermalV1_1_3Lib|RedfishPocPkg/Library/RfishCS/edk2/Thermal/v1_1_3/Lib.inf
  ThermalV1_1_4Lib|RedfishPocPkg/Library/RfishCS/edk2/Thermal/v1_1_4/Lib.inf
  ThermalV1_1_5Lib|RedfishPocPkg/Library/RfishCS/edk2/Thermal/v1_1_5/Lib.inf
  ThermalV1_1_6Lib|RedfishPocPkg/Library/RfishCS/edk2/Thermal/v1_1_6/Lib.inf
  ThermalV1_2_0Lib|RedfishPocPkg/Library/RfishCS/edk2/Thermal/v1_2_0/Lib.inf
  ThermalV1_2_1Lib|RedfishPocPkg/Library/RfishCS/edk2/Thermal/v1_2_1/Lib.inf
  ThermalV1_2_2Lib|RedfishPocPkg/Library/RfishCS/edk2/Thermal/v1_2_2/Lib.inf
  ThermalV1_2_3Lib|RedfishPocPkg/Library/RfishCS/edk2/Thermal/v1_2_3/Lib.inf
  ThermalV1_2_4Lib|RedfishPocPkg/Library/RfishCS/edk2/Thermal/v1_2_4/Lib.inf
  ThermalV1_2_5Lib|RedfishPocPkg/Library/RfishCS/edk2/Thermal/v1_2_5/Lib.inf
  ThermalV1_3_0Lib|RedfishPocPkg/Library/RfishCS/edk2/Thermal/v1_3_0/Lib.inf
  ThermalV1_3_1Lib|RedfishPocPkg/Library/RfishCS/edk2/Thermal/v1_3_1/Lib.inf
  ThermalV1_3_2Lib|RedfishPocPkg/Library/RfishCS/edk2/Thermal/v1_3_2/Lib.inf
  ThermalV1_3_3Lib|RedfishPocPkg/Library/RfishCS/edk2/Thermal/v1_3_3/Lib.inf
  ThermalV1_3_4Lib|RedfishPocPkg/Library/RfishCS/edk2/Thermal/v1_3_4/Lib.inf
  ThermalV1_4_0Lib|RedfishPocPkg/Library/RfishCS/edk2/Thermal/v1_4_0/Lib.inf
  ThermalV1_4_1Lib|RedfishPocPkg/Library/RfishCS/edk2/Thermal/v1_4_1/Lib.inf
  ThermalV1_4_2Lib|RedfishPocPkg/Library/RfishCS/edk2/Thermal/v1_4_2/Lib.inf
  ThermalV1_5_0Lib|RedfishPocPkg/Library/RfishCS/edk2/Thermal/v1_5_0/Lib.inf
  ThermalV1_5_1Lib|RedfishPocPkg/Library/RfishCS/edk2/Thermal/v1_5_1/Lib.inf
  TriggersV1_0_0Lib|RedfishPocPkg/Library/RfishCS/edk2/Triggers/v1_0_0/Lib.inf
  TriggersCollectionLib|RedfishPocPkg/Library/RfishCS/edk2/TriggersCollection/Lib.inf
  UpdateServiceV1_0_0Lib|RedfishPocPkg/Library/RfishCS/edk2/UpdateService/v1_0_0/Lib.inf
  UpdateServiceV1_0_1Lib|RedfishPocPkg/Library/RfishCS/edk2/UpdateService/v1_0_1/Lib.inf
  UpdateServiceV1_0_2Lib|RedfishPocPkg/Library/RfishCS/edk2/UpdateService/v1_0_2/Lib.inf
  UpdateServiceV1_0_3Lib|RedfishPocPkg/Library/RfishCS/edk2/UpdateService/v1_0_3/Lib.inf
  UpdateServiceV1_0_4Lib|RedfishPocPkg/Library/RfishCS/edk2/UpdateService/v1_0_4/Lib.inf
  UpdateServiceV1_0_5Lib|RedfishPocPkg/Library/RfishCS/edk2/UpdateService/v1_0_5/Lib.inf
  UpdateServiceV1_1_0Lib|RedfishPocPkg/Library/RfishCS/edk2/UpdateService/v1_1_0/Lib.inf
  UpdateServiceV1_1_1Lib|RedfishPocPkg/Library/RfishCS/edk2/UpdateService/v1_1_1/Lib.inf
  UpdateServiceV1_1_2Lib|RedfishPocPkg/Library/RfishCS/edk2/UpdateService/v1_1_2/Lib.inf
  UpdateServiceV1_1_3Lib|RedfishPocPkg/Library/RfishCS/edk2/UpdateService/v1_1_3/Lib.inf
  UpdateServiceV1_1_4Lib|RedfishPocPkg/Library/RfishCS/edk2/UpdateService/v1_1_4/Lib.inf
  UpdateServiceV1_2_0Lib|RedfishPocPkg/Library/RfishCS/edk2/UpdateService/v1_2_0/Lib.inf
  UpdateServiceV1_2_1Lib|RedfishPocPkg/Library/RfishCS/edk2/UpdateService/v1_2_1/Lib.inf
  UpdateServiceV1_2_2Lib|RedfishPocPkg/Library/RfishCS/edk2/UpdateService/v1_2_2/Lib.inf
  UpdateServiceV1_2_3Lib|RedfishPocPkg/Library/RfishCS/edk2/UpdateService/v1_2_3/Lib.inf
  UpdateServiceV1_3_0Lib|RedfishPocPkg/Library/RfishCS/edk2/UpdateService/v1_3_0/Lib.inf
  UpdateServiceV1_3_1Lib|RedfishPocPkg/Library/RfishCS/edk2/UpdateService/v1_3_1/Lib.inf
  UpdateServiceV1_4_0Lib|RedfishPocPkg/Library/RfishCS/edk2/UpdateService/v1_4_0/Lib.inf
  VirtualMediaV1_0_0Lib|RedfishPocPkg/Library/RfishCS/edk2/VirtualMedia/v1_0_0/Lib.inf
  VirtualMediaV1_0_2Lib|RedfishPocPkg/Library/RfishCS/edk2/VirtualMedia/v1_0_2/Lib.inf
  VirtualMediaV1_0_3Lib|RedfishPocPkg/Library/RfishCS/edk2/VirtualMedia/v1_0_3/Lib.inf
  VirtualMediaV1_0_4Lib|RedfishPocPkg/Library/RfishCS/edk2/VirtualMedia/v1_0_4/Lib.inf
  VirtualMediaV1_0_5Lib|RedfishPocPkg/Library/RfishCS/edk2/VirtualMedia/v1_0_5/Lib.inf
  VirtualMediaV1_1_0Lib|RedfishPocPkg/Library/RfishCS/edk2/VirtualMedia/v1_1_0/Lib.inf
  VirtualMediaV1_1_1Lib|RedfishPocPkg/Library/RfishCS/edk2/VirtualMedia/v1_1_1/Lib.inf
  VirtualMediaV1_1_2Lib|RedfishPocPkg/Library/RfishCS/edk2/VirtualMedia/v1_1_2/Lib.inf
  VirtualMediaV1_1_3Lib|RedfishPocPkg/Library/RfishCS/edk2/VirtualMedia/v1_1_3/Lib.inf
  VirtualMediaV1_2_0Lib|RedfishPocPkg/Library/RfishCS/edk2/VirtualMedia/v1_2_0/Lib.inf
  VirtualMediaV1_2_1Lib|RedfishPocPkg/Library/RfishCS/edk2/VirtualMedia/v1_2_1/Lib.inf
  VirtualMediaV1_2_2Lib|RedfishPocPkg/Library/RfishCS/edk2/VirtualMedia/v1_2_2/Lib.inf
  VirtualMediaCollectionLib|RedfishPocPkg/Library/RfishCS/edk2/VirtualMediaCollection/Lib.inf
  VLanNetworkInterfaceV1_0_0Lib|RedfishPocPkg/Library/RfishCS/edk2/VLanNetworkInterface/v1_0_0/Lib.inf
  VLanNetworkInterfaceV1_0_1Lib|RedfishPocPkg/Library/RfishCS/edk2/VLanNetworkInterface/v1_0_1/Lib.inf
  VLanNetworkInterfaceV1_0_2Lib|RedfishPocPkg/Library/RfishCS/edk2/VLanNetworkInterface/v1_0_2/Lib.inf
  VLanNetworkInterfaceV1_0_3Lib|RedfishPocPkg/Library/RfishCS/edk2/VLanNetworkInterface/v1_0_3/Lib.inf
  VLanNetworkInterfaceV1_0_4Lib|RedfishPocPkg/Library/RfishCS/edk2/VLanNetworkInterface/v1_0_4/Lib.inf
  VLanNetworkInterfaceV1_0_5Lib|RedfishPocPkg/Library/RfishCS/edk2/VLanNetworkInterface/v1_0_5/Lib.inf
  VLanNetworkInterfaceV1_0_6Lib|RedfishPocPkg/Library/RfishCS/edk2/VLanNetworkInterface/v1_0_6/Lib.inf
  VLanNetworkInterfaceV1_1_0Lib|RedfishPocPkg/Library/RfishCS/edk2/VLanNetworkInterface/v1_1_0/Lib.inf
  VLanNetworkInterfaceV1_1_1Lib|RedfishPocPkg/Library/RfishCS/edk2/VLanNetworkInterface/v1_1_1/Lib.inf
  VLanNetworkInterfaceV1_1_2Lib|RedfishPocPkg/Library/RfishCS/edk2/VLanNetworkInterface/v1_1_2/Lib.inf
  VLanNetworkInterfaceCollectionLib|RedfishPocPkg/Library/RfishCS/edk2/VLanNetworkInterfaceCollection/Lib.inf
  VolumeV1_0_0Lib|RedfishPocPkg/Library/RfishCS/edk2/Volume/v1_0_0/Lib.inf
  VolumeV1_0_1Lib|RedfishPocPkg/Library/RfishCS/edk2/Volume/v1_0_1/Lib.inf
  VolumeV1_0_2Lib|RedfishPocPkg/Library/RfishCS/edk2/Volume/v1_0_2/Lib.inf
  VolumeV1_0_3Lib|RedfishPocPkg/Library/RfishCS/edk2/Volume/v1_0_3/Lib.inf
  VolumeCollectionLib|RedfishPocPkg/Library/RfishCS/edk2/VolumeCollection/Lib.inf
  ZoneV1_0_0Lib|RedfishPocPkg/Library/RfishCS/edk2/Zone/v1_0_0/Lib.inf
  ZoneV1_0_1Lib|RedfishPocPkg/Library/RfishCS/edk2/Zone/v1_0_1/Lib.inf
  ZoneV1_0_2Lib|RedfishPocPkg/Library/RfishCS/edk2/Zone/v1_0_2/Lib.inf
  ZoneV1_0_3Lib|RedfishPocPkg/Library/RfishCS/edk2/Zone/v1_0_3/Lib.inf
  ZoneV1_1_0Lib|RedfishPocPkg/Library/RfishCS/edk2/Zone/v1_1_0/Lib.inf
  ZoneV1_1_1Lib|RedfishPocPkg/Library/RfishCS/edk2/Zone/v1_1_1/Lib.inf
  ZoneV1_1_2Lib|RedfishPocPkg/Library/RfishCS/edk2/Zone/v1_1_2/Lib.inf
  ZoneV1_2_0Lib|RedfishPocPkg/Library/RfishCS/edk2/Zone/v1_2_0/Lib.inf
  ZoneV1_2_1Lib|RedfishPocPkg/Library/RfishCS/edk2/Zone/v1_2_1/Lib.inf
  ZoneCollectionLib|RedfishPocPkg/Library/RfishCS/edk2/ZoneCollection/Lib.inf
  LogEntryV1_4_2Lib|RedfishPocPkg/Library/RedfishCSLib/edk2/LogEntry/v1_4_2/Lib.inf
  redfisherrorV1_0_0Lib|RedfishPocPkg/Library/RedfishCSLib/edk2/redfisherror/v1_0_0/Lib.inf
  redfisherrorV1_0_0Lib|RedfishPocPkg/Library/RedfishCSLib/edk2/redfisherror/v1_0_0/Lib.inf
  redfisherrorV1_0_0Lib|RedfishPocPkg/Library/RedfishCSLib/edk2/redfisherror/v1_0_0/Lib.inf
  redfisherrorV1_0_0Lib|RedfishPocPkg/Library/RedfishCSLib/edk2/redfisherror/v1_0_0/Lib.inf
